### PR TITLE
simple typed static works!

### PR DESCRIPTION
**Pull request by grosu**
@cos: this passes all the tests.

However, I did not modify the .out files, for the reasons explained in previous issues.  If you can take care of #2098 then you can go ahead and also uncomment https://github.com/kframework/k/blob/master/k-distribution/tutorial/2_languages/1_simple/tests/config.xml#L14 so the tests get included, too.  Then we can mark SIMPLE as done!

Now I'm moving to KOOL typed static.

### CODE REVIEW

**Comment by daejunpark** [comment]
@grosu please consider #2107 if you have any issue regarding cell fragments.

**Comment by grosu** [comment]
Got it.  I didn't need it yet, currently stuck with parsing.

**Comment by cos** [comment]
shall I merge this?

**Comment by grosu** [comment]
@cos yes, please.  hm, interesting that tests passed.  anyway, yes, please merge this, too.

**Comment by cos** [comment]
There's something funky on master. Even though we have green with the PRs, the master has been failing (timeout) for a few hours. It doesn't even reach the actual tests because it times out here:

```
Downloading: http://office.runtimeverification.com:8888/repository/snapshots/org/kframework/k/parent/4.0-beta4-SNAPSHOT/maven-metadata.xml
```

@dwightguth, do you have any idea?

**Pull request merged**
