### PR TITLE
fix for strategy priorities

### PR DESCRIPTION
**Pull request by cos**
addresses #1921

### CODE REVIEW

**Comment by dwightguth** [comment]
this is not going to fix this. I know because there are currently warnings in this module that I don't see anything being done to fix.

**Comment by cos** [comment]
@dwightguth, again, please be explicit. Copy-paste the warnings that you see or be explicit on how you make them appear. I fixed the warnings that I saw when running the unit tests will `.ALL` warnings.

**Comment by dwightguth** [comment]
This is not really particularly complex:

```
module TEST
endmodule
```

```
kompile test.k -w all
```

**Comment by cos** [comment]
It is strange that the errors do not appear in unit tests -- and it's not the `.print`. Anyhow, are those legitimate warnings? @radumereuta?

**Comment by cos** [comment]
```
[Warning] Compiler: Variable 'A' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(1001,10,1001,70)
[Warning] Compiler: Variable 'A' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(983,10,983,103)
[Warning] Compiler: Variable 'A' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(991,10,991,129)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(1001,10,1001,70)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(1003,10,1003,51)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(1005,10,1005,35)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(1007,10,1007,40)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(983,10,983,103)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(984,10,984,53)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(985,10,985,37)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(986,10,986,39)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(988,10,988,48)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(989,10,989,49)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(991,10,991,129)
[Warning] Compiler: Variable 'B' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(992,10,992,77)
[Warning] Compiler: Variable 'C' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(988,10,988,48)
[Warning] Compiler: Variable 'C' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(989,10,989,49)
[Warning] Compiler: Variable 'C' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(991,10,991,129)
[Warning] Compiler: Variable 'C' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(992,10,992,77)
[Warning] Compiler: Variable 'CONFIGURATION' was not declared. Assuming sort K.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(994,10,994,104)
[Warning] Compiler: Variable 'CONFIGURATION' was not declared. Assuming sort K.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(996,10,996,60)
[Warning] Compiler: Variable 'S' was not declared. Assuming sort Strategy.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(981,10,981,50)
[Warning] Compiler: Variable 'THIS_CONFIGURATION' was not declared. Assuming
sort K.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(983,10,983,103)
[Warning] Compiler: Variable 'THIS_CONFIGURATION' was not declared. Assuming
sort K.
    Source(/Users/cos/workspaces/k/k-distribution/target/release/k/lib/java/../../include/builtin/domains.k)
    Location(991,10,991,129)
```

**Comment by radumereuta** [comment]
Already discussed this in private but I'm going to write it here too for documentation:
There is an empty test which runs with `-w all` in order to catch hidden warnings from the `/include` directory.
The idea is that we don't want to clutter the users hidden warning list with our stuff from the include directory.

**Comment by dwightguth** [comment]
looks good, thanks. One thing I'm curious about though. Is there a reason you are manually programming in a THIS_CONFIGURATION variable instead of just using the #configuration builtin?

**Comment by cos** [comment]
I didn't know #configuration existed. Last time I looked through that code and needed it, there was no such functionality. The only way to add it as a hook at the time, and also now, would have been to add it to TermContext/GlobalContext and I didn't like that solution. 

That being said, if it's already there, I will think about replacing `THIS_CONFIGURATION` with the hook. I'm not sure about using a hook because it reads the global context from a field that's linked from the terms, so it can be affected by problems like the one in the other thread. The `THIS_CONFIGURATION` variable is a very simple solution to the same problem.

**Comment by cos** [comment]
Though, I admit, `THIS_CONFIGURATION` also required a non-local change in the new LHS-RHS variable consistency check, which is not that nice.

**Pull request merged**
