### PR TITLE
remove xml backend ( #50 )

### PR DESCRIPTION
**Pull request by osa1**
issue #50

### CODE REVIEW

**Comment by traiansf** [comment]
Shouldn't we also remove xstream from the dependent libraries?

**Comment by osa1** [comment]
Right .. Added one more commit to remove xstream library. But I'm still not sure it it's complete. `DefinitionReader` still does some xml reading(using `XmlLoader`) .. are those also related with XML backend?

**Comment by traiansf** [comment]
I don't think so.  It seems to be using DOM to parse configuration patterns.

**Comment by osa1** [comment]
OK, this patch should be done, then.

**Pull request merged**
