### PR TITLE
Use unix domain sockets for kserver on linux and mac os x (more secure)

### PR DESCRIPTION
**Pull request by dwightguth**
@bmmoore please review. This diff should make nailgun secure on Mac OS X and Linux. It is still insecure on Windows, but now only on machines that have multiple concurrent users.

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by bmmoore** [comment]
Code looks fine, but why did it just finally pass? What are we not seeing on this page that explains why it didn't just finally get lucky?

**Comment by dwightguth** [comment]
The race:
1. Thread 1 calls read() on socket
2. Thread 2 closes socket
3. Thread 3 opens a new file
4. Thread 1 resumes read(), corrupts newly opened file.

I am still working on a fix to this issue that is reliable. It's turning
into a huge pain, but the reason why it's intermittently passing now is
that I figured out what went wrong and have implemented a fix that is buggy
but works some of the time.

**Comment by grosu** [comment]
Can you find this race with RV-Predict?

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@bmmoore please review. I seem to have been able to isolate the bugs so that the only issue is that the local sockets are slower than the tcp sockets. I have disabled the local sockets by default and put them under the option `kserver -l`. This is sufficient for my needs for the company; we can come back to this issue and make them the default at a later date if need be.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by bmmoore** [comment]
Ok, now that you've set the default back.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Closing this for now so that pushes don't screw up the jenkins server. I'll reopen this at a later date once I have time to spend on trying to get this to work.

**Pull request closed without merging**
