### PR TITLE
Fix for requires with relative paths in the equivalence checker

### PR DESCRIPTION
**Pull request by theo25**
This is the fix for requires relative paths. I have rebased it on top of master.

@daejunpark

### CODE REVIEW

**Comment by daejunpark** [comment]
This PR will be subsumed by #2217.

@theo25 could you please check if #2217 (or keq branch 6e40fb5f0ec35925aa1ef387636690e7cedcad9e)  fixed your problem?

**Comment by theo25** [comment]
@daejunpark No, the problem is still there when trying with this branch/commit.

**Comment by daejunpark** [comment]
@theo25 oh, sorry I forgot to say that you should use another command. `Kapi.main` is deprecated and will be deleted. Please use this command:

```
$ keq <prelude.smt2> <def0.k> <mod0> <def1.k> <mod1> <def2.k> <mod2> <spec.k>
```

For example,

```
$ cd k-distribution/tests/equiv/test2
$ keq ../../../../k-distribution/include/z3/basic.smt2 imp.k IMP imp1.k IMP imp2.k IMP if_spec.k
```

You can find more examples in https://github.com/kframework/k/blob/keq/k-distribution/tests/equiv/test2/run.sh

**Comment by theo25** [comment]
@daejunpark I am actually using the org.kframework.main.Main class from the shell module with -keq as first argument and the rest of the arguments as you suggested. Is this also deprecated?

**Comment by daejunpark** [comment]
@theo25 you're right. Now I see what's the problem. I'll incorporate your fix into the PR.

**Comment by daejunpark** [comment]
@theo25 could you please check if #2225 fixed the original problem?

**Comment by theo25** [comment]
@daejunpark Yes it did. Thanks!

**Comment by daejunpark** [comment]
closed via #2225

**Pull request closed without merging**
