### PR TITLE
Fix regular expression. Adding the "|" operator to Token to allow for

### PR DESCRIPTION
**Pull request by radumereuta**
String declarations.

This comes in response to one of the emails sent over the k-user mailing list asking for a way to declare their own types of strings. I had to ask Michael to modify the BasicParser grammar to allow for "|" inside Token.

Once this is merged I can generalize strings and respond to the user.

### CODE REVIEW

**Comment by dwightguth** [comment]
I'm having trouble figuring out precisely what this is doing. Can you add a unit test?

**Comment by radumereuta** [comment]
Dwight, I've added a regression test as you requested. Can you revisit this pull request with a higher priority?
I'm trying to answer some users on the k-user mailing list.

**Comment by dwightguth** [comment]
I said unit test for a reason... This is a perfect candidate for a unit test, one which takes a string of a production and runs it through the basic parser and checks the AST of the result. That way we add only a couple hundred milliseconds to the test suite instead of 10 extra seconds.

**Comment by radumereuta** [comment]
Dwight, please have another look at this.

**Comment by dwightguth** [comment]
lgtm. Who worked on the Basic Parser originally? Who should review this? If that person was you or isn't still around, get Michael to weigh in on this.

**Comment by radumereuta** [comment]
It is Michael who wrote the javacc version of the BasicParser, and he is the one that did this change yesterday when we were working on the newparser.

**Comment by dwightguth** [comment]
Okay. Then merge it.

**Pull request merged**
