### PR TITLE
Added a check to test for duplicate module names.

### PR DESCRIPTION
**Pull request by radumereuta**
Got a weird nasty NPE because I didn't have this check.

### CODE REVIEW

**Comment by radumereuta** [comment]
@dwightguth please review.

**Comment by dwightguth** [comment]
:/ looks like we don't currently obey this restriction. You need to fix agent.

**Comment by radumereuta** [comment]
@traiansf I think agent is under your keep.
Do you need that module name to be called 'IO' ?
I found a bug in the parser which I can avoid by having unique module names.

If you disagree with having unique names for modules, then I need a semantics on what to do if that happens (merge the modules, replace...)

**Comment by chathhorn** [comment]
Shouldn't you change the standard module names if you're going to enforce this? I don't see why the standard modules should get all the good names.

**Comment by dwightguth** [comment]
We could make the builtin modules begin with "K-"... e.g. K-IO.

**Comment by radumereuta** [comment]
@dwightguth, @traiansf please review.

**Comment by traiansf** [comment]
lgtm :-)

**Pull request merged**
