### PR TITLE
release preparation

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by dwightguth** [comment]
It would be nice to include a K 3-to-4 migration guide in this.

**Comment by cos** [comment]
@radumereuta, could you add a bit of information about the parser here? I can do it otherwise.

**Comment by radumereuta** [comment]
@cos, done, have a look.

**Comment by cos** [comment]
@radumereuta, looks good. only made a small change.

**Comment by radumereuta** [comment]
You are right, it sounds better.

**Comment by cos** [comment]
return-object.kool is flaky... it consistently works on my computer but fails intermittently on codeship. As this PR does not touch code, disregard that error for now.

**Comment by grosu** [comment]
Looks good.  Merging.

**Pull request merged**
