### PR TITLE
display "Empty substitution" instead of ""

### LINKED ISSUE #2098: Empty substitution should be explicit
Continuing the example in #2097:

```
D:\github\grosu\k\k-distribution\tutorial\2_languages\1_simple\2_typed\1_static>krun ..\programs\diverse\factorial.simple --pattern "<tasks> T </tasks>"
Search results:

Solution 1:
T:K -->
.TaskCellBag
D:\github\grosu\k\k-distribution\tutorial\2_languages\1_simple\2_typed\1_static>krun ..\programs\diverse\factorial.simple --pattern "<tasks> .TaskCellBag </tasks>"
[Error] Inner Parser: Parse error: unexpected character '<'.
        Source(<command line>)
        Location(1,22,1,23)
D:\github\grosu\k\k-distribution\tutorial\2_languages\1_simple\2_typed\1_static>krun ..\programs\diverse\factorial.simple --pattern "<tasks> .Bag </tasks>"
Search results:

Solution 1:
D:\github\grosu\k\k-distribution\tutorial\2_languages\1_simple\2_typed\1_static>
```

Probably `.Bag` is somewhat overloaded for all cell types, which is OK for now.  However, it is not nice to end a user message `Solution 1:`.  In K3.6 we used to report:

```
Search results:

Solution 1:
Empty substitution
```

This looks better and we don't have to change many of our `.out` files in the tutorial.

### PR DESCRIPTION
**Pull request by cos**
closes #2098

### CODE REVIEW

**Comment by cos** [comment]
@grosu, merge if passing

**Comment by grosu** [comment]
@cos, looks good but please also modify the top config file of simple to include the simple typed static tests.

**Comment by cos** [comment]
This may not pass -- I have an `--update-out` running on my computer in case there are any differences.

**Comment by cos** [comment]
`--update-out` showed no changes, so this should pass.

**Pull request merged**
