### PR TITLE
improvements over BasicTransformer and some other stuff

### PR DESCRIPTION
**Pull request by osa1**
important parts:

5c897bd : explicit copying operations replaced with `shallowCopy` method call for consistency.
769015b : as mentioned by Michael on the mailing list, added calls to superclass visitors on return values. My intuition was that every visitor method should end with a transform call to it's arguments superclass, except the base class which is `ASTNode`.

Please note that I couldn't run test suite because I still don't have SSH access to test machines.

### CODE REVIEW

**Comment by traiansf** [comment]
Dear Omer,

Whatever you did broke the java rewrite engine.  To reproduce:
go to 
dist/examples/java_rewrite_engine/simple/untyped
$ kompile -ml simple-untyped
$ krun -backend java-symbolic -smt none ../../../simple/untyped/programs/diverse/collatz.simple
Exception in thread "main" java.lang.ClassCastException: org.kframework.backend.java.kil.Variable cannot be cast to org.kframework.kil.Term
        at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:489)
        at org.kframework.kil.CollectionBuiltin.accept(CollectionBuiltin.java:76)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transform(KILtoBackendJavaKILTransformer.java:247)
        at org.kframework.kil.Cell.accept(Cell.java:266)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transform(KILtoBackendJavaKILTransformer.java:230)
        at org.kframework.kil.Cell.accept(Cell.java:266)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transform(KILtoBackendJavaKILTransformer.java:230)
        at org.kframework.kil.Cell.accept(Cell.java:266)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transform(KILtoBackendJavaKILTransformer.java:230)
        at org.kframework.kil.Cell.accept(Cell.java:266)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transform(KILtoBackendJavaKILTransformer.java:230)
        at org.kframework.kil.Cell.accept(Cell.java:266)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transform(KILtoBackendJavaKILTransformer.java:230)
        at org.kframework.kil.Cell.accept(Cell.java:266)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transform(KILtoBackendJavaKILTransformer.java:439)
        at org.kframework.kil.Rule.accept(Rule.java:78)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transform(KILtoBackendJavaKILTransformer.java:513)
        at org.kframework.kil.Definition.accept(Definition.java:121)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:82)
        at org.kframework.backend.java.symbolic.JavaSymbolicKRun.<init>(JavaSymbolicKRun.java:60)
        at org.kframework.krun.Main.obtainKRun(Main.java:285)
        at org.kframework.krun.Main.normalExecution(Main.java:302)
        at org.kframework.krun.Main.execute_Krun(Main.java:1184)
        at org.kframework.main.Main.main(Main.java:80)

**Comment by osa1** [comment]
Interesting, it worked fine on my machine:

```
➜  untyped git:(refactor2) ✗ kompile -ml simple-untyped.k 
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/map.k
        Location: (45,3,45,75)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/map.k
        Location: (59,3,59,54)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/map.k
        Location: (64,3,64,58)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/map.k
        Location: (69,3,69,46)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/set.k
        Location: (15,3,16,14)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/set.k
        Location: (17,3,18,23)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/set.k
        Location: (22,3,23,23)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/set.k
        Location: (32,3,32,65)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/set.k
        Location: (37,3,37,51)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/bag.k
        Location: (15,3,15,65)
[Warning] Critical: Unsupported map pattern in the rule left-hand side
        File: /home/omer/K/k/dist/include/builtins/bag.k
        Location: (20,3,20,51)

➜  untyped git:(refactor2) ✗ krun -backend "java-symbolic" -smt none ../../../simple/untyped/programs/diverse/collatz.simple
Testing Collatz' conjecture up to what number? 5
Testing Collatz' conjecture for n = 1 ... Done! It took 0 steps.
Testing Collatz' conjecture for n = 2 ... Done! It took 1 steps.
Testing Collatz' conjecture for n = 3 ... Done! It took 7 steps.
Testing Collatz' conjecture for n = 4 ... Done! It took 2 steps.
Testing Collatz' conjecture for n = 5 ... Done! It took 5 steps.
Done.  It appears to hold.
[1493, 7.399 s]
<T>
    <threads>
        .Bag
    </threads>                                                                                                                                                                                                                                 
    <genv>
        collatz |-> 0
        main |-> 1
    </genv>
    <store>
        0 |-> lambda ( n , ({ ((var ((s = 0), .List{","}) ;) ((print ( (
          "Testing Collatz' conjecture for n = ", (n, " ... ")) ) ;) ((while 
          ( (n > 1) ) ({ (((s = (s + 1)) ;) (if ( (n == ((n / 2) * 2)) ) ({ (
          (n = (n / 2)) ;) }) else ({ ((n = ((3 * n) + 1)) ;) }))) })) (print
           ( ("Done! It took ", (s, " steps.\n")) ) ;)))) }) )
        1 |-> lambda ( .List{","} , ({ ((print ( 
          "Testing Collatz' conjecture up to what number? " ) ;) ((var ((m = 
          read ( )), .List{","}) ;) ((for ( (var ((i = 1), .List{","}) ;) (i 
          <= m) ; (++ i) ) ({ ((collatz ( i )) ;) })) (print ( 
          "Done.  It appears to hold.\n" ) ;)))) }) )
        10 |-> 1
        11 |-> 2
        12 |-> 1
        13 |-> 5
        2 |-> 5
        3 |-> 6
        4 |-> 1
        5 |-> 0
        6 |-> 1
        7 |-> 1
        8 |-> 1
        9 |-> 7
    </store>
    <busy>
        .Set
    </busy>
    <terminated>
        SetItem(0)
    </terminated>
    <in>
        ListItem(#buffer ( "" ))
        ListItem(#istream ( 0 ))
    </in>
    <out>
        ListItem(#ostream ( 1 ))
        ListItem(#buffer ( "" ))
    </out>
    <nextLoc>
        14
    </nextLoc>
</T>
➜  untyped git:(refactor2) ✗ 
```

**Comment by osa1** [comment]
rebased with latest master and still works on my machine.

**Comment by traiansf** [comment]
Hm.

I've tested both on fslwork and on my machine and I get the same exception.
Can anybody else test?
I have no idea what is going on at the moment

best wishes,
Traian

2013/9/27 Ömer Sinan Ağacan notifications@github.com

**Comment by osa1** [comment]
Are you merging my patches on nightly branch? I'm working on master.

**Comment by traiansf** [comment]
same here. also, nightly and master are now synchronized.

best wishes,
Traian

2013/9/27 Ömer Sinan Ağacan notifications@github.com

**Comment by osa1** [comment]
OK, now I'm also getting same error. Working on it.

**Comment by osa1** [comment]
https://github.com/osa1/k/commit/6b53e991ba5983e3689c44326ca3bdfed2776aec#L0L356 this line causes the problem, and I think I did it correct. This probably means we have some other bug which is triggered after fixing this code.

**Comment by osa1** [comment]
Okay, this is probably beyond me. I tried kompiling same file for maude backend, and this assertion is failed: https://github.com/kframework/k/blob/master/javasources/KTool/src/org/kframework/kil/DataStructureBuiltin.java#L226

This is because https://github.com/kframework/k/blob/master/javasources/KTool/src/org/kframework/kil/DataStructureBuiltin.java#L188 here `baseTerm().size() == 0` and so viewBase is not set.

But I have no idea what does that class do so I don't know what to do now. I'm confident that my changes on BasicTransformer are correct, my guess is that this correction cause some other bug to appear.

**Comment by traiansf** [comment]
Andrei, Could you take a look into it?

best wishes,
Traian

2013/9/28 Ömer Sinan Ağacan notifications@github.com

**Comment by osa1** [comment]
Here's the smallest K program that I could reproduce the error:

```
require "io/io.k"

module SIMPLE-UNTYPED
  imports IO

  configuration
    <out stream="stdout"> .MyList </out>

endmodule
```

or

```
require "io/uris.k"
require "builtins/list.k"

module SIMPLE-UNTYPED
  imports LIST
  imports URIS

  rule (MyListItem(#ostream(_:Int)) MyListItem(#noIO) => .MyList) 
       MyListItem(#buffer(_))

  configuration
    <out stream="stdout"> .MyList </out>

endmodule
```

**Comment by osa1** [comment]
here's an interesting observation: this bug already exists without my patch. dist/examples/java_rewrite_engine/tutorial/4_imp++/imp.k this file fails with same error when compiled with current master branch.

**Comment by osa1** [comment]
I think the problem is related with one of the DataStructureBuiltin visitors. 

For example, there's an unimplemented visitor method  https://github.com/kframework/k/blob/master/javasources/KTool/src/org/kframework/kil/visitors/Transformer.java#L65

Also, transformer and visitor interfaces have different number of methods -- which suggests at least one of the has bugs.

**Comment by osa1** [comment]
It turned out refactoring visitors needs more thinking .. I removed that commit and now it passes tests.

(also rebased on latest master)

**Pull request merged**
