### PR TITLE
Hotfix/scala 2.11.6 and Eclipse fix

### PR DESCRIPTION
**Pull request by cos**
**please review**

### CODE REVIEW

**Comment by cos** [comment]
Jenkins, test this please.

**Comment by cos** [comment]
@dwightguth, this should be ok to merge, and hopefully will fix the Eclipse problems.

**Comment by radumereuta** [comment]
So I shouldn't use `last()`? Can you explain what happened there?

**Comment by cos** [comment]
Eclipse was giving some weird errors, it didn't like `head` and `last`.

**Pull request merged**
