### PR TITLE
try to fix #1606 - should restrict mutable terms to only outside the …

### LINKED ISSUE #1606: data race on field org.kframework.backend.java.kil.CellCollection$Cell.content
I got this race report when testing kool-typed-static. At first I thought it would be an easy fix, but then I realized that it shows that we are sharing mutable terms (i.e., `CellCollection` & `CellCollection$Cell`) between several kruns. Isn't problematic? How does it happen? @andreistefanescu @dwightguth What do you think?

```
Data race on field org.kframework.backend.java.kil.CellCollection$Cell.content: {{{
    Concurrent read in thread T300 (locks held: {})
 ---->  at org.kframework.backend.java.kil.CellCollection$Cell.content(CellCollection.java:45)
        at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:512)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:608)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.SymbolicUnifier.symbolicUnify(SymbolicUnifier.java:70)
        at org.kframework.backend.java.symbolic.SymbolicUnifier.symbolicUnify(SymbolicUnifier.java:61)
        at org.kframework.backend.java.kil.ConstrainedTerm.unify(ConstrainedTerm.java:190)
        at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStepByRule(SymbolicRewriter.java:206)
        at org.kframework.backend.java.symbolic.SymbolicRewriter.lambda$computeRewriteStep$68(SymbolicRewriter.java:154)
        at org.kframework.backend.java.symbolic.SymbolicRewriter$$Lambda$198.apply(Unknown:n/a)
        at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:163)
        at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:80)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.conventionalRewriteRun(JavaSymbolicExecutor.java:114)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:137)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T300 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T289 (locks held: {})
 ---->  at org.kframework.backend.java.kil.CellCollection$Cell.setContent(CellCollection.java:49)
        at org.kframework.backend.java.rewritemachine.KAbstractRewriteMachine.rewrite(KAbstractRewriteMachine.java:98)
        at org.kframework.backend.java.rewritemachine.KAbstractRewriteMachine.rewrite(KAbstractRewriteMachine.java:64)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:232)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T289 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

### PR DESCRIPTION
**Pull request by dwightguth**
…definition

@yilongli I am pretty sure this is a real bug but I'm not 100% sure that it's the same bug that caused the race that you are reporting. Can you please check whether you are still getting subject terms shared across requests after you apply this patch?

### CODE REVIEW

**Comment by yilongli** [comment]
I am going to test it with RV-Predict, but a better invariant would be that class `CellCollection` & `CellCollection$Cell` are always accessed by a single thread.

**Comment by yilongli** [comment]
Yes, RV-Predict still reports races inside `CellCollection`.

**Comment by yilongli** [comment]
Can you rebase this pull request on the latest master to include the recent fixes of data races? There is a lot of noise in RV-Predict's result now.

**Comment by dwightguth** [comment]
@yilongli what about now? I am not 100% happy with this fix because it may make some programs slightly slower, but I'd like to know whether it seems to solve the issue before I try and determine whether I can come up with a faster solution than this.

**Comment by dwightguth** [comment]
Test seems to be passing still. Are you okay with merging this if I disable the assertion, or do you want to try RV-predict as well first?

**Comment by yilongli** [comment]
Looks good to me. I don't see the failure on kool-typed-static anymore and RV-Predict is happy about it. Feel free to merge it if you don't want to work on a faster solution. Thanks.

**Comment by dwightguth** [comment]
The code in question is a corner case for concrete-only execution in the Java backend, which is likely to be less important going forward since the OCAML backend is much faster for the same task. So I am probably not going to worry about the performance too much especially since the patch doesn't seem to have had an appreciable impact on the time ktest takes to run.

I have added the change to the nailgun version to this patch as well. If tests pass, I will go ahead and merge this.

**Pull request merged**
