### PR TITLE
change default output to directory of source file instead of working dir...

### PR DESCRIPTION
**Pull request by dwightguth**
...ectory

@yilongli please review

@pdaian @grosu FYI

### CODE REVIEW

**Comment by yilongli** [comment]
Modify the documentation as well?

**Comment by dwightguth** [comment]
@yilongli please re-review

**Comment by yilongli** [comment]
lgtm

**Comment by dwightguth** [comment]
Race conditions... @yilongli when will rv-predict be ready to try?

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by yilongli** [comment]
when @traiansf revives the asynchronous logging and implements an online prediction algorithm?

**Pull request merged**
