### PR TITLE
fix #800

### LINKED ISSUE #800: Ktest incorrectly executes simple typed static on Windows
```
C:\Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\
1_static> ktest tests\config.xml
Kompile the language definitions...(1 in total)
SUCCESS
Generate PDF files...(1 in total)
SUCCESS
Running C:\Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\
2_typed\1_static\simple-typed-static.k programs... (34 in total, 0 with input, 3
4 with output, 0 with error)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\diver
se\collatz.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\dwi
ght.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"] f
ailed with error (time: 25 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\diver
se\factorial.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\d
wight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"]
 failed with error (time: 33 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\diver
se\dekker.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\dwig
ht.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"] fa
iled with error (time: 47 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\diver
se\div-nondet.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 48 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\diver
se\higher-order.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\User
s\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_stati
c"] failed with error (time: 41 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_01.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 24 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\diver
se\matrix.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\dwig
ht.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"] fa
iled with error (time: 32 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\diver
se\sortings.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\dw
ight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"]
failed with error (time: 28 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_02.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 20 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_03.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 22 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_05.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 20 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_04.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 36 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_06.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 23 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_08.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 25 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_07.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 44 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_09.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 25 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_10.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 30 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_11.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 26 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_12.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 24 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_13.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 21 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_14.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 25 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\excep
tions\exceptions_15.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\
Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_s
tatic"] failed with error (time: 19 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_01.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 20 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_02.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 18 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_03.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 24 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_04.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 25 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_05.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 27 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_06.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 20 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_07.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 42 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_08.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 34 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_10.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 33 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_09.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 56 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_11.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 30 ms)
ERROR: ["C:\Users\dwight.guth\Downloads\k-stable\k\bin\krun.bat" "C:\Users\dwigh
t.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\programs\threa
ds\threads_12.simple" "--pattern" "<tasks>.Bag</tasks>" "--directory" "C:\Users\
dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\1_static"
] failed with error (time: 30 ms)
FAIL

FAIL (see details above)
----------------------------
Definitions kompiled: 1 (time: 0'8'' elapsed, 0'8'' CPU)
PDF posters kompiled: 1 (time: 0'27'' elapsed, 0'27'' CPU)
Programs krun: 34 (time: 0'0'' elapsed, 0'0'' CPU)
Total time: 0'35'' elapsed, 0'35'' CPU
----------------------------


C:\Users\dwight.guth\Downloads\k-stable\k\tutorial\2_languages\1_simple\2_typed\
1_static>
```

I suspect but have not confirmed that this is an incompatibility between how krun is invoked in a shell and how it is invoked by ktest using exec. The programs execute correctly when run as indicated by the output on the terminal.

### PR DESCRIPTION
**Pull request by osa1**
I'll let Jenkins run test suite on Linux and I'm manually running test suite on my Windows laptop. It's very slow so it'll probably take several hours.

In the meantime I need reviews. It turns out that the problem is really about string escaping. Based on the observation that I'm using the same shell on both Linux and Windows(bash) but still having different results(on Linux it works OK, on Windows it fails as shown in #800), I assumed that it's only related with the platform and not the shell. So I treated Windows as a special case in `getXYZCmd()` methods.

I also assumed that the test suite is running fine on OSX so special case is really Windows and not Linux.

### CODE REVIEW

**Comment by dwightguth** [comment]
looks good. Let me know if the tests pass on your machine, so I can merge this. Or if they don't in which case there is likely another linux-specific bug.

**Comment by osa1** [comment]
Several tests failed on my Windows system. I inspected the outputs a bit and I found:
- Tests that use `--prove` are failing because backend is having trouble loading Z3 library. I didn't make any changes related with Z3 loading, so maybe this deserves it's own issue. (e.g. unmodified framework but `--prove` doesn't work because of a class loader error, this doesn't sound good)
- `newparser` tests are failing because ktest is failing to find `kast` executable. It runs this command:
  
  ```
  krun --parser "kast --parser newprogram" a.test
  ```
  
  and it's failing with `error while running process: Cannot run program "kast"`. If I run this instead:
  
  ```
  krun --parser "kast.bat --parser newprogram" a.test
  ```
  
  it works fine. I think we're having another bug here.
- Some of the failed cases are reported wrong because of #680. (I think we can ignore this since after merging to master this will be fixed)

@dwightguth Are those(kast and `--prove`) tests working on `unified-builtins2` on Windows?

**Comment by radumereuta** [comment]
Regarding the new parser issues. That would be an acceptable limitation to ktest if it would provide the possibility to call kast somehow and compare it's output. What I'm doing there, is actually kind of a hack because I can't test the output another way.

**Comment by osa1** [comment]
Another approach might be to add some variable support to `ktest` so that a `$KAST` in a config file would be replaced with `kast` on Linux/OSX but `kast.bat` on Windows. We can even let users define the variables and values that depend on current platform.

@radumereuta also, even if I fix kast executable name, those tests are failing because of some wrong unsafe casts.

**Comment by radumereuta** [comment]
My advice would be to ignore them for now. We should spend resources trying to implement the features we do want, not on patches to make them work right now.

**Pull request merged**
