### PR TITLE
add negative contracts on KilProperty

### PR DESCRIPTION
**Pull request by dwightguth**
Technically the KilProperty contracts are ternary, not binary: a kilproperty can either be required/ensured, or it can be forbidden/destroyed, or it can be unspecified. Trying to implement a ternary EnumSet with an undefined state seemed overkill for this, so I just created negative annotations. If someone has a better solution, I'm open to it.

### CODE REVIEW

**Comment by dwightguth** [comment]
@andreistefanescu or @traiansf Can you review this?

**Comment by traiansf** [comment]
looks good.  But I would like to get more insight on what is this good for and patterns of usage.

**Comment by andreistefanescu** [comment]
lgtm

**Comment by dwightguth** [comment]
@traiansf does this additional comment address your concern?

**Comment by traiansf** [comment]
@dwightguth Yes, it does. please feel free to merge.

**Pull request merged**
