### PR TITLE
Fast unification3

### PR DESCRIPTION
**Pull request by andreistefanescu**
do not review

### CODE REVIEW

**Comment by andreistefanescu** [comment]
@dwightguth please review

**Comment by dwightguth** [comment]
what is the effect of this diff on execution and verification performance?

**Comment by andreistefanescu** [comment]
The effect on performance is minimal. This is just refactoring the common code in pattern matching and unification. I moved from double dispatch to if-then-else to mirror Yilong's work in `NonACPatternMatcher`, but I'm not seeing any noticeable improvements in performance. Next steps are to eliminate `NonACPatternMatcher` and to add an unification based `KAbstractRewriteMachine`.

**Comment by dwightguth** [comment]
looks great!

**Pull request merged**
