### PR TITLE
Delete stuff

### PR DESCRIPTION
**Pull request by dwightguth**
FYI @liyili2 @andreiarusoaie @dlucanu @daniel-ionut-vicol @ciobaca 

In order to make the core of the K framework easier to maintain, and in light of the new approach to a modular architecture, I am removing components that belong to each of you. If you have any desire to refer to them in the future, they are available for download at this repository under the tag v3.4.1, which tags commit 397620c

I imagine you may be interested in being able to continue to use your tools with the latest version of the framework, so I encourage you all to attempt to convert these components into K modules, using the java backend module as a guide. If you find that this is more difficult than you expect, or that you believe you should have access to a core API of the tool when developing these modules, please email me or find me on Google Hangouts and we'll talk about the right way to provide the interface that you need.

Please let me know if you have any questions.

@yilongli @grosu please review

### CODE REVIEW

**Comment by yilongli** [comment]
I know a few obsolete stuffs that were only referred to by the simulation. I will go find and remove them after you merge this pull request.

**Comment by yilongli** [comment]
you forgot to remove `kagreg.bat`

**Comment by dwightguth** [comment]
There is no kagreg.bat, there never was.

**Comment by grosu** [comment]
Thank you, Dwight.

I would just like to tell everybody that this step, namely removing about 10k LOC from the K code base, while somehow drastic, it was really needed.  Dwight has completely modularized the Java rewrite engine, demonstrating how to add components to K modularly.  This way, we will all focus on having a crystal clean implementation of core K, where we only introduce new code very conservatively, which will thus be easy to maintain and understand.  Everything else will be a module.  Research projects by universities, research or commerciat tools by companies, etc., all will be just plug-and-play modules. Nobody will be in charge of maintaining those modules except their authors, and the quality of their code will not affect the overall quality of the K code.

Dwight, Cosmin, and others, put a lot of effort into making this happen, and I am grateful to them.  Dwight offered to help whoever needs help to make their old code into a module.  Please also include me in such discussions, because I want to make sure we have smooth transitions.

Grigore

**Comment by dlucanu** [comment]
I am glad that Dwight finalised to modularise the Java rewrite engine, this is a good news. So, do we have a methodology for modularisation? If yes, where can we find it? 
We are pressed by time to maintain our tool as they are referred in papers under review. We are willing to add our stuff as modules asap, but for that we have to know how.
Thanks.

**Comment by grosu** [comment]
The plan is that Dwight will write a Wiki page explaining how to do this.  Then that wiki will be improved as others try it out.

Thanks for your support, Dorel!
Grigore

**Comment by dwightguth** [comment]
Wiki is here: https://github.com/kframework/k/wiki/Creating-a-Module

Please let me know if anything seems unclear about it. I didn't try to explain everything, just the basics. Eventually developers of the modules will just have to get a basic familiarity with the core in order to know what they can and can't do.

**Comment by grosu** [comment]
Considering the importance of this page from here on,

```
https://github.com/kframework/k/wiki/Creating-a-Module
```

I insist that everybody using it should bring their contribution to improving it!  If you believe that certain things are not explained well and you need to talk to Dwight in order to understand them, then please add more explanations on this wiki, or kindly ask Dwight to do it.  We want to get to a point where people can extend K with new modules without any help from us.

Thanks, Dwight!

Grigore

**Pull request merged**
