### PR TITLE
More parallel ktest

### PR DESCRIPTION
**Pull request by osa1**
[WIP]

This turned out to be more involved then I expected, because ktest was designed for this. We knew that it's possible to improve concurrency of it but we decided to go with simpler approach at the time.

This is blocked by #1059 .

TODO:
- [x] KTest should check for required `-kompiled` directories when `--skip kompile` is provided, otherwise krun tests will fail. (this was working before this patch)
- [x] Posix-only steps are not implemented.

I'll organize commits before merging this.

### CODE REVIEW

**Comment by osa1** [comment]
Hmm, build failed with:

```
ERROR: ['/var/lib/jenkins/jobs/k-framework-pull-requests-maven/workspace/k/k-distribution/target/release/k/bin/krun' '/var/lib/jenkins/jobs/k-framework-pull-requests-maven/workspace/k/k-distribution/samples/java_rewrite_engine/tutorial/2_languages/1_simple/1_untyped/verification/comm_assoc.simple' '--prove' 'verification/comm_assoc_spec.k' '--directory' 'verification'] failed with error (time: 80528 ms)
error was: Aborted (core dumped)
```

Does this look familiar to anyone? @yilongli ?

**Comment by yilongli** [comment]
The z3 library seems to crash again. Adding `--z3-executable` to the krun option should solve the problem.

**Comment by osa1** [comment]
This is ready for reviews.

The problem with Z3 is disappeared, but some others appeared randomly. I think we'll have that Z3 problem randomly again in the future, maybe we can have a different issue for tracking that.

I'll try to figure why some other tests randomly failed after some completely unrelated commit.

I think we had good improvement. Not a very precise benchmark, but Jenkins took 41 min before that and 34 min with this patch.

Another improvement is that this is now safe: https://github.com/osa1/k/commit/8653e49ae11c153b42c795b02cc4fe89fda6c0d8 When detected multiple test cases that compile to same directory, ktest compiles only once. So we can now distribute tests for same definition to multiple files.

I guess only disadvantage of this approach is that we have slightly worse ktest output. This is because we're not running different steps(scripts, ktest, pdf, krun) in order, they now all interleaved. (only ordering is that in a test case kompile process runs before kruns) This also effects statistics. For example, we can't know how long kompile steps took because kompile steps are interleaved with PDFs and kruns etc.

For reviewers:

There is actually two things going on:
1. A new class `TaskQueue` which does most of the job. I recommend reviewing it from the file instead of the diff.
2. Rest is just moving things from `TestSuite` to `TestCase` and minor things like passing an extra argument to `KRunProgram`, introducing some new fields etc.

It'd also be nice if I could get some feedback on current KTest output (you can see it in Jenkins page). It's mostly same, a bit less verbose but also less informative as mentioned above.

**Comment by osa1** [comment]
Again, I can't reproduce errors in both rvwork and my laptop. @yilongli do they look familiar to you by any chance?

**Comment by yilongli** [comment]
So there are two failures. The first one is another z3 library crash. Adding `--z3-executable` should solve the problem. The second failure seems like an insufficient timeout limit of z3 because the formula in the final configuration is clearly unsat. You can try to set a larger `--z3-cnstr-timeout` for this example (default is 50ms).

**Comment by osa1** [comment]
Thanks Yilong.

This is now working and ready for reviews/merge.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Since this test concerns both ktest and threading, I decided to run it a second time just in case it catches some nondeterministic errors. If the tests pass the second time, go ahead and merge this. We'll deal with further issues if they arise.

**Pull request merged**
