### PR TITLE
remove "remove preincluded rules" for rules in k definitions

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Transient git failure on jenkins. Retesting.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@andreistefanescu please review

**Comment by andreistefanescu** [comment]
lgtm

**Pull request merged**
