### PR TITLE
Fixing start symbol for command line arguments.

### PR DESCRIPTION
**Pull request by radumereuta**
@cos or @daejunpark please review.

### CODE REVIEW

**Comment by daejunpark** [comment]
@radumereuta Does this fix the IO problem?

**Comment by radumereuta** [comment]
No, it's unrelated.
But I think I'm hitting flaky tests, because I tested the failing tests on my computer and they worked.
The second time I run the tests, different examples failed.

**Comment by cos** [comment]
@radumereuta, comment out the flaky tests and document them here: #1959

**Comment by radumereuta** [comment]
I don't think the tests are flaky. I think there is something in krun which fails from time to time.
Over time I noticed a wide variety of tests that fail, and all of them at krun.

**Comment by cos** [comment]
Yes, there are several tests failing, but generally in lambda/lambda++. I think there is some unwanted non-determinism there. If you could spare some time to look into the non-determinism, that would be great. Otherwise, my suggestion is to comment out the tests and document the fact.

**Comment by grosu** [comment]
Again: First and foremost, make sure that RV-Predict does NOT report any data-race in K.  How can we claim that we have a program verifier if it has random behaviors, in particular data-races?

Please: do not comment definition/tests out only because you feel like they are flaky.  Unless you guys bring evidence that the lambda definitions or tests are indeed non-deterministic due to mistakes in their design, I would say that it is a WRONG approach to remove them only because they are inconvenient.  And if they have indeed non-deterministic (but equivalent) results, which may well happen in the case of environment-based definitions of lambda calculi because the closures can get different locations, then why don't you run those tests with the search option and thus get even more powerful tests out of them?

**Comment by radumereuta** [comment]
I decided to merge this into the module qualified sorts. It will be reviewed with the rest.
It is more likely the bug that made these tests flaky will be fixed there.

**Pull request closed without merging**
