### PR TITLE
fix failure to report errors

### PR DESCRIPTION
**Pull request by dwightguth**
@radumereuta please review

This is why you didn't see an error message on the command line. Next time something similar happens, please file an issue; it's a bug.

### CODE REVIEW

**Comment by radumereuta** [comment]
lgtm

**Comment by radumereuta** [comment]
Actually, I get this: 

```
d:\work\js-semantics-float-bug>kompile -v js.k --backend java --debug --noprelude
com.beust.jcommander.ParameterException: Unknown option: --noprelude
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:738)
        at com.beust.jcommander.JCommander.parse(JCommander.java:281)
        at com.beust.jcommander.JCommander.parse(JCommander.java:264)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:209)
        at org.kframework.utils.inject.JCommanderModule.jcommander(JCommanderModule.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:115)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1000)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:996)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:93)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:109)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:279)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1000)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1046)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:996)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1035)
        at org.kframework.main.Main.main(Main.java:40)
[Error] Critical: Unknown option: --noprelude

d:\work\js-semantics-float-bug>
```

What's with the stack trace? Is this related to the bug we talked about yesterday?

**Comment by dwightguth** [comment]
congratulations, you specified --debug, that's why the stack trace.

**Comment by radumereuta** [comment]
hmm... right.

**Comment by grosu** [comment]
Still, we should give a better error message here.  I would have had no idea what was going on here.

**Comment by radumereuta** [comment]
The error message would be this:

```
d:\work\js-semantics-float-bug>kompile -v js.k --backend java --X
[Error] Critical: Unknown option: --X

d:\work\js-semantics-float-bug>
```

I just miss used it.

**Comment by dwightguth** [comment]
@grosu the point is that users should not specify the --debug flag, only developers. It exists to facilitate debugging of the tool, and is not designed to be used by end users.

**Comment by grosu** [comment]
But they may, by mistake.  Dorel did it, and so would I if I wanted to debug my definition.  We should not use such a common name for an option targeting the developers.  And no matter what name we choose, we should output some message to make it clear what it is, not just throw an exception (even if it is under construction).  Something like this:

---K Developer Debugger.  Exit if not a developer.---

etc.

**Pull request merged**
