### PR TITLE
Remove code that calls KompileOptions.Backend.java()

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
@andreistefanescu please review

I made it so that variables in heating/cooling rules in the Java backend are sorted to KItem, it didn't seem to break anything. We can still explore strongly typing them again later, I just don't want to spend a bunch of time fixing stuff right now that isn't strictly related to the path I'm on.

**Comment by andreistefanescu** [comment]
Looks good so far. You can merge when the tests pass.

**Comment by dwightguth** [comment]
Closing in favor of #858

**Comment by dwightguth** [comment]
@grosu your stuff looks good to me, can you do a spot check on commit e1acca5?

@andreistefanescu the new stuff you haven't reviewed yet starts with 15f18bd. The only stuff that has changed since are definitions and ktest files. I am going to merge this if Grigore is happy, but you're welcome to take a second look too if you want.

**Comment by andreistefanescu** [comment]
Looks good. We also found the nondeterministic tests in the java backend, and I think we just excluded them.

**Comment by dwightguth** [comment]
I have no idea why KernelC failed to parse. I'm going to run it again, there's not much else I can try.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
