### PR TITLE
Reorganize maven into separate modules in order to prepare for modularization

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@cos please review

Unfortunately you are going to have to review these files manually since it's an enormous diff mostly consisting of renames without file changes. I am including below the list of files which contain actually changed lines of code, in case it makes your job easier. Sorry for the inconvenience.

```
:000000 100644 0000000... 59a472d... A  k-core/pom.xml
:100644 100644 45d17f1... 8628f86... R097   include/html/k-definition.css   k-distribution/include/html/k-definition.css
:100644 100644 53c9fba... 84fea3c... R096   include/html/k-documentation.css    k-distribution/include/html/k-documentation.css
:000000 100644 0000000... 40a26b3... A  k-distribution/pom.xml
:100644 100644 d8b5934... c3d88c9... R091   src/main/assembly/bin.xml   k-distribution/src/main/assembly/bin.xml
:100755 100755 f8c8d51... 3b24a67... R085   src/main/scripts/bin/kagreg k-distribution/src/main/scripts/bin/kagreg
:100755 100755 b9e0508... ff3de53... R086   src/main/scripts/bin/kast   k-distribution/src/main/scripts/bin/kast
:100755 100755 9998a1c... ac04184... R085   src/main/scripts/bin/kompile    k-distribution/src/main/scripts/bin/kompile
:100755 100755 33dd573... 5ba057b... R086   src/main/scripts/bin/kpp    k-distribution/src/main/scripts/bin/kpp
:100755 100755 126ed8a... 8e7a42b... R087   src/main/scripts/bin/krun   k-distribution/src/main/scripts/bin/krun
:100755 100755 64567ba... 9d4d15f... R085   src/main/scripts/bin/ktest  k-distribution/src/main/scripts/bin/ktest
:100755 100755 eb74ee8... b1d5751... R080   tests/regression/java-rewrite-engine/io/test1/prepare.sh    k-distribution/tests/regression/java-rewrite-engine/io/test1/prepare.sh
:100644 100644 d782aa1... bdf981d... R093   tutorial/1_k/1_lambda/README.md k-distribution/tutorial/1_k/1_lambda/README.md
:100644 100644 da3b8c6... 20b0db3... R098   tutorial/1_k/1_lambda/lesson_1/README.md    k-distribution/tutorial/1_k/1_lambda/lesson_1/README.md
:100644 100644 136a1c9... 32951cb... R098   tutorial/1_k/1_lambda/lesson_2/README.md    k-distribution/tutorial/1_k/1_lambda/lesson_2/README.md
:100644 100644 8d1d6c1... 1cd2960... R097   tutorial/1_k/1_lambda/lesson_3/README.md    k-distribution/tutorial/1_k/1_lambda/lesson_3/README.md
:100644 100644 31f87bf... b0acd6e... R097   tutorial/1_k/1_lambda/lesson_4/README.md    k-distribution/tutorial/1_k/1_lambda/lesson_4/README.md
:100644 100644 beb19fe... 796651d... R098   tutorial/1_k/1_lambda/lesson_5/README.md    k-distribution/tutorial/1_k/1_lambda/lesson_5/README.md
:100644 100644 7f4cf9a... 35bcbd7... R097   tutorial/1_k/1_lambda/lesson_6/README.md    k-distribution/tutorial/1_k/1_lambda/lesson_6/README.md
:100644 100644 ef99d1f... a615816... R098   tutorial/1_k/1_lambda/lesson_7/README.md    k-distribution/tutorial/1_k/1_lambda/lesson_7/README.md
:100644 100644 71a9cf4... 3ab375d... R097   tutorial/1_k/1_lambda/lesson_8/README.md    k-distribution/tutorial/1_k/1_lambda/lesson_8/README.md
:100644 100644 491052b... 2afb2dc... R097   tutorial/1_k/1_lambda/lesson_9/README.md    k-distribution/tutorial/1_k/1_lambda/lesson_9/README.md
:100644 100644 c3ecabd... 1812ee5... R091   tutorial/1_k/3_lambda++/README.md   k-distribution/tutorial/1_k/3_lambda++/README.md
:100644 100644 a347643... f248dbc... R098   tutorial/1_k/3_lambda++/lesson_1/README.md  k-distribution/tutorial/1_k/3_lambda++/lesson_1/README.md
:100644 100644 ce6eab7... acc1101... R099   tutorial/1_k/3_lambda++/lesson_2/README.md  k-distribution/tutorial/1_k/3_lambda++/lesson_2/README.md
:100644 100644 128b37d... 53d38d8... R096   tutorial/1_k/3_lambda++/lesson_3/README.md  k-distribution/tutorial/1_k/3_lambda++/lesson_3/README.md
:100644 100644 5615f79... 0cd2fec... R097   tutorial/1_k/3_lambda++/lesson_4/README.md  k-distribution/tutorial/1_k/3_lambda++/lesson_4/README.md
:100644 100644 6d290c1... 898ed66... R098   tutorial/1_k/3_lambda++/lesson_5/README.md  k-distribution/tutorial/1_k/3_lambda++/lesson_5/README.md
:100644 100644 35cc743... b06d81c... R089   tutorial/1_k/3_lambda++/lesson_6/README.md  k-distribution/tutorial/1_k/3_lambda++/lesson_6/README.md
:100644 100644 ef1ca1d... 9fbcb83... R086   tutorial/1_k/5_types/README.md  k-distribution/tutorial/1_k/5_types/README.md
:100644 100644 59ebcd6... 7212369... R099   tutorial/1_k/5_types/lesson_1/README.md k-distribution/tutorial/1_k/5_types/lesson_1/README.md
:100644 100644 43d49a4... 2493d27... R096   tutorial/1_k/5_types/lesson_2/README.md k-distribution/tutorial/1_k/5_types/lesson_2/README.md
:100644 100644 cffcfac... daa461a... R095   tutorial/1_k/5_types/lesson_3/README.md k-distribution/tutorial/1_k/5_types/lesson_3/README.md
:100644 100644 2ea5821... dc3db1c... R099   tutorial/1_k/5_types/lesson_4/README.md k-distribution/tutorial/1_k/5_types/lesson_4/README.md
:100644 100644 d5344b9... e4b448c... R097   tutorial/1_k/5_types/lesson_5/README.md k-distribution/tutorial/1_k/5_types/lesson_5/README.md
:100644 100644 97ffc0f... b8cb04d... R098   tutorial/1_k/5_types/lesson_7/README.md k-distribution/tutorial/1_k/5_types/lesson_7/README.md
:100644 100644 9caebd7... 723c776... R097   tutorial/1_k/5_types/lesson_8/README.md k-distribution/tutorial/1_k/5_types/lesson_8/README.md
:100644 100644 2b3c5da... 7307a61... R078   tutorial/1_k/5_types/lesson_9.5/README.md   k-distribution/tutorial/1_k/5_types/lesson_9.5/README.md
:100644 100644 95de9ef... c633a21... R099   tutorial/1_k/5_types/lesson_9/README.md k-distribution/tutorial/1_k/5_types/lesson_9/README.md
:100644 100644 675edac... e594294... R080   tutorial/1_k/README.md  k-distribution/tutorial/1_k/README.md
:100644 100644 fdf2ed0... 2d68e50... R097   tutorial/NOTES.md   k-distribution/tutorial/NOTES.md
:100644 100644 3e069fa... b61a6ff... R099   tutorial/README.md  k-distribution/tutorial/README.md
:100644 100644 b2bac47... 81793a1... M  pom.xml
:100644 100644 14092a0... 779d2d6... M  src/README.md
:100644 100644 6afd320... cf5a142... M  src/main/config/checkstyle-copyright.xml
:100755 100755 4c5805c... 6a03b5d... M  src/main/scripts/add_copyright
```

**Comment by yilongli** [comment]
In the above list, the only non-trivial changes are actually a small fraction:

```
:000000 100644 0000000... 59a472d... A  k-core/pom.xml
:100644 100644 45d17f1... 8628f86... R097   include/html/k-definition.css   k-distribution/include/html/k-definition.css
:100644 100644 53c9fba... 84fea3c... R096   include/html/k-documentation.css    k-distribution/include/html/k-documentation.css
:000000 100644 0000000... 40a26b3... A  k-distribution/pom.xml
:100644 100644 d8b5934... c3d88c9... R091   src/main/assembly/bin.xml   k-distribution/src/main/assembly/bin.xml
:100755 100755 f8c8d51... 3b24a67... R085   src/main/scripts/bin/kagreg k-distribution/src/main/scripts/bin/kagreg
:100755 100755 b9e0508... ff3de53... R086   src/main/scripts/bin/kast   k-distribution/src/main/scripts/bin/kast
:100755 100755 9998a1c... ac04184... R085   src/main/scripts/bin/kompile    k-distribution/src/main/scripts/bin/kompile
:100755 100755 33dd573... 5ba057b... R086   src/main/scripts/bin/kpp    k-distribution/src/main/scripts/bin/kpp
:100755 100755 126ed8a... 8e7a42b... R087   src/main/scripts/bin/krun   k-distribution/src/main/scripts/bin/krun
:100755 100755 64567ba... 9d4d15f... R085   src/main/scripts/bin/ktest  k-distribution/src/main/scripts/bin/ktest
:100644 100644 b2bac47... 81793a1... M  pom.xml
:100644 100644 14092a0... 779d2d6... M  src/README.md
:100644 100644 6afd320... cf5a142... M  src/main/config/checkstyle-copyright.xml
:100755 100755 4c5805c... 6a03b5d... M  src/main/scripts/add_copyright
```

The other changes are merely fixing missing copyright information. @cos It would be great if you can take some time to review it. Right now, I don't have the expertise to catch potential errors related to maven.

**Comment by yilongli** [comment]
@dwightguth it seems that you forgot to change other windows scripts under `k-distribution/src/main/scripts/bin/`.

**Comment by yilongli** [comment]
@dwightguth I think I have understood how it works and it looks good to me. However, somebody else should also take a look.

**Comment by cos** [comment]
Ok, so, if I understand this correctly, k-core contains all the source code and unit tests, while k-distribution contains everything else put in a K distribution, including integration tests. 

So, if I don't care about running integration tests, I should be able to simply take just k-core, compile it, and run all unit tests, right?

Hm... we're now reaching both the source directory and the samples, integration tests, etc. means going through one extra folder. How do you see working with this? Will we have two Eclipse/IntelliJ projects instead of one? I've tried `mvn eclipse:eclipse` in the parent folder and in both dependent modules. If fails in the parent and k-distribution. It passes in k-core but the resulting Eclipse project doesn't compile. The Eclipse project is still rooted in the parent directory and it says it is missing resource dependences.

**Comment by dwightguth** [comment]
I did some research and it looks like in a multi-module project, you are expected to run `mvn install` before running `mvn eclipse:eclipse`. When you do this, it builds successfully. @cos, can you re-review, especially the last couple commits?

**Comment by dwightguth** [comment]
there's that intermittent error on Jenkins with compiling cil again. It's hard to determine what's causing it when there's no race condition and it can't be reproduced. I guess I'll just run it again.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
