### PR TITLE
eliminated next_id from README.md

### PR DESCRIPTION
**Pull request by grosu**
minor edits

### CODE REVIEW

**Comment by dwightguth** [comment]
Looks good but I believe you need to fix copyright.

**Comment by grosu** [comment]
This is old stuff, then I forgot to merge long ago.
@andreistefanescu please check.

**Comment by andreistefanescu** [comment]
Looks good. The errors are due to missing copyright. You can add
`<!-- Copyright (c) 2010-2015 K Team. All Rights Reserved. -->`
on the first line of each file.

**Comment by cos** [comment]
@grosu, do you still want to this merged? It seems to be very close.

**Comment by grosu** [comment]
Thanks for the reminder, @cos, and for not deleting this PR.

**Pull request merged**
