### PR TITLE
Progress on verification in k4.0

### PR DESCRIPTION
**Pull request by andreistefanescu**

### CODE REVIEW

**Comment by radumereuta** [comment]
Did you realize that merge broke master?
Is this a mistake? Nobody reviewed this PR.

**Comment by grosu** [comment]
What?  @cos, I hope things are set up that we are still doing code reviews.  Also, why does codeship build notifier lets us merge PRs which break the master?

**Comment by cos** [comment]
Yes, we are still doing code reviews. Andrei probably merged by mistake -- it's no big deal, I will revert it now. Also, it's not about codeship. No third-party tool can stop a user from hitting the merge button or manually pushing a merge.

**Comment by dwightguth** [comment]
True, although it's possible to configure github so that you can't push to master without either the tests passing in a pull request, or admin permissions

**Comment by andreistefanescu** [comment]
@cos thank you for reverting. I accidentally pushed from the command line in the main repository instead of my own fork, and I did not realized. Github seems to have detected that as a merge into the master.

**Pull request merged**
