### PR TITLE
Feature/split k cell from top cell transform

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by cos** [comment]
@bmmoore, please review when it passes the tests

**Comment by bmmoore** [comment]
The label constants should follow the style we've used everywhere else, of exposing a static final string field named in uppercase. Looks okay otherwise. (In particular, calling it as an accessor I'm not quite sure if those values are sometimes meant to vary).

**Comment by cos** [comment]
Jenkins, test this please.

**Comment by bmmoore** [comment]
Looks good.

**Pull request merged**
