### PR TITLE
Add hook function4 printing java double

### PR DESCRIPTION
**Pull request by xiaohe27**
@laurayuwen @dwightguth This pull request aims to provide a function for java-semantics so that the floating point (specifically the type 'double') data type in java can be printed by k the same way as java does.

### CODE REVIEW

**Comment by dwightguth** [comment]
Haha, no. This belongs in the Java semantics, not the K standard library.

**Comment by andreistefanescu** [comment]
Actually, this is a reasonable format. What is the standard format for other languages? I think C/C++ and Python have a similar format. Can you check if it is the same?

**Comment by dwightguth** [comment]
Neither C, Python, nor Java yield the same result that I observe:

Java, String.valueOf: `2.2250738585072014E-308`
Python, float.**repr**: `2.2250738585072014e-308`
C, printf("%f", ...): `0.000000`

This is quite aside from the fact that all three of these languages implement completely disparate string formatting languages that a semantics of these languages logically would have to deal with regardless, for which this method is entirely ill-suited. I maintain that this is simply not suitable material for the K standard library.

**Comment by xiaohe27** [comment]
Yes, you are right, I agree. I'll try to implement this using K instead :)

**Pull request closed without merging**
