### PR TITLE
Clean up symbolic rewriter

### PR DESCRIPTION
**Pull request by yilongli**
do not review yet

### CODE REVIEW

**Comment by yilongli** [comment]
I mistakenly thought that the `FastRuleMatcher` already worked for unification so I was trying to connect it to my CFG generation. Anyway, I separated the potentially useful change in this pull request. @andreistefanescu please review

**Comment by andreistefanescu** [comment]
Why is side condition evaluation moved in the matcher?

**Comment by yilongli** [comment]
Because I think the automata should eventually take into account side conditions of the rules. For example, the same side condition should be evaluated only once for different rules. For now, it only simplifies the code on the SymbolicRewriter side a little bit.

**Comment by andreistefanescu** [comment]
You can merge it, but this part of the code is work in progress, so it is very likely to go through several changes in the future.

**Comment by dwightguth** [comment]
@yilongli just a note for the future I agree we should eventually be able to use an automata to evaluate side conditions, but it will have to happen only for functions that are not marked impure and do not recusively call functions marked impure.

**Pull request merged**
