### PR TITLE
Adding option to make warnings errors and fail running to all tools.

### PR DESCRIPTION
**Pull request by radumereuta**
@dwightguth please review.
I don't know how to change the configuration of jenkins to provide the -w2e tag.

### CODE REVIEW

**Comment by radumereuta** [comment]
Jenkins retest this please

**Comment by radumereuta** [comment]
I think I broke Jenkins. Can someone have a look here?
It didn't get my latest commit, and it started giving OutOfMemory exceptions.

**Comment by radumereuta** [comment]
Jenkins retest this please

**Comment by dwightguth** [comment]
It seems there is something wrong with your code to suppress the flag on certain tests, because it doesn't seem to be working...

**Comment by radumereuta** [comment]
I noticed. The problem is that I can't reproduce it on my computer, it only fails on jenkins.

**Comment by dwightguth** [comment]
Try testing it on linux. There is at least a tiny amount of platform-specific code in ktest, so it could be because you are running on windows somehow...

**Comment by dwightguth** [comment]
lgtm

**Pull request merged**
