### PR TITLE
Imppp

### PR DESCRIPTION
**Pull request by grosu**
Updated IMP++ in the tutorial to use the unified builtins.

However, it seems that `krun spawn.imp --search` does not work.  It given no results, which is wierd.

Andrei Stefanescu, Traian, and Yilong, can you please review this and check what's the problem with `--search`?

Thanks,
Grigore

btw: I ran into several errors and enhancement opportunities, which I will report separately as issues.

### CODE REVIEW

**Comment by andreistefanescu** [comment]
One quick suggestion: you do not need to inject the environment Rho in order to put it in the k cell (Map is now subsorted to K).

**Comment by dlucanu** [comment]
Is this subsorting available in both backends?

**Comment by grosu** [comment]
This is SOOOOO nice!  Thanks, Andrei.  I made the change and everything works (except for the --search thing, which I reported already and I think you guys need to fix).

**Comment by traiansf** [comment]
I might have identified the issue, but I'm not sure if I'm the most
qualified to fix it.

There was a mechanism to disable i/o when doing search (setting a barrier
in the stream cells). which apparently does not work anymore, and thus
Maude attempts to send output through the socket.  Does anybody remember
messing with this recently?

**Comment by andreistefanescu** [comment]
Does search work in the java backend?

**Comment by traiansf** [comment]
The java backend does not work at all.

**Comment by dwightguth** [comment]
I will own fixing the issue with search since it was my code originally
once upon a time. expect a code review sometimes tomorrow or early
Wednesday at the latest.

**Comment by grosu** [comment]
@traiansf @andreistefanescu can you guys please take a quick look at this and let me know if it is OK?  It should be a 3 minute job for you now.  Once you approve it, I have the approval from Dwight to merge.

**Comment by andreistefanescu** [comment]
Look good. Make sure you change the copyright from (C) to (c) in order to pass the tests.

**Comment by grosu** [comment]
Thanks!  Done.

Grigore

**Comment by traiansf** [comment]
looks good

**Comment by grosu** [comment]
Dwight, can we merge this?  I see that the tests failed, so I am not sure.

**Comment by dwightguth** [comment]
I will check what tests failed tomorrow and if they look right, I will
merge. Or you can inspect yourself. Basically, all the tests associated
with definitions you have fixed should pass except whatever is affected by
the bug with io and search that Andrei needs to fix.

**Comment by dwightguth** [comment]
Looks like you need to change the copyright to the lowercase (c). I suggest next time you run into this situation you click the "details" link to bring up Jenkins, and view the build log to see if it ran ktest or if it just failed with a copyright check.

**Comment by grosu** [comment]
But I've done that already, that was my last commit.  That's why the error message did not make sense to me.

Grigore

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Never mind, I know what happened. the checkstyle xml file hadn't been merged from master and it was still expecting capital C. I fixed it and am rerunning the tests. If everything looks good, I will merge this.

**Pull request merged**
