### PR TITLE
try to make variables include _

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
@radumereuta seems to work just fine. Are you okay with this being merged? it will significantly benefit my ability to verify C programs.

**Comment by radumereuta** [comment]
lgtm, but this is a K design decision, so @grosu do you approve that variables can contain underscore in their name?

**Comment by grosu** [comment]
But they already do, don't they?  _1, _2, etc., are variables generated by unification in combination with the ?X, ?Y, etc., variables.  Actually, I think people should even be allowed to use _1, _2, etc., in their rules the same way as they use _ alone.

Grigore

**Comment by radumereuta** [comment]
@andreistefanescu can you clarify what _1, _2 are? Because I can tell you they weren't parsed as variables.

**Comment by dwightguth** [comment]
I believe they are variables, they are just not parsed by the semantics (being generated by the rewriter) and are therefore not subject to the syntax of variables.

**Pull request merged**
