### PR TITLE
Fixing the regex for String and KString (again).

### PR DESCRIPTION
**Pull request by radumereuta**
@dwightguth please review.

### CODE REVIEW

**Comment by daejunpark** [comment]
you may want to drop the hook, or leave a comment for preventing confusion.

**Comment by radumereuta** [comment]
Right, @dwightguth  does the hook in both of them do anything right now?

**Comment by dwightguth** [comment]
It does not, but you should keep it in kast.k and remove it in domains.k

**Comment by dwightguth** [comment]
lgtm. Merge when you fix the hooks

**Comment by radumereuta** [comment]
Jenkins retest this please

**Pull request merged**
