### PR TITLE
Tracing functionality added.

### PR DESCRIPTION
**Pull request by alexgyori**
Implementation of tracing functionality for k.
Adds a flag to kompile(--trace) in the java backend.
This will introduce a cell that will track at runtime all the rules that are triggered.

### CODE REVIEW

**Comment by dlucanu** [comment]
This functionality should work for the Maude backend as well. How the rule labels are defined? I ask this because a rule may have zero, one or more tags associated, and the same tag may be shared by more rules.

**Comment by dwightguth** [comment]
What are next steps here?

**Comment by alexgyori** [comment]
I believe I fixed Michael’s points. Is there anything else I should address?

Alex

**Comment by dwightguth** [comment]
ok to test

**Comment by dwightguth** [comment]
Yeah, can you run this on a simple example and show me the inputs/outputs?

**Comment by alexgyori** [comment]
There is a wiki page i wrote: KSeCo usage at https://github.com/alexandrugyori/k/wiki/KSeCo-usage
Let me know if that does not suffice.

**Comment by dwightguth** [comment]
Sorry, I should have been clearer. I want to see example outputs, not information about what the output is generally.

**Comment by alexgyori** [comment]
A concrete example of output is below.
it is obtained by running in the directory K_HOME/samples/java_rewrite_engine/simple/untyped/:
../../../../bin/kompile --trace --backend java simple-untyped.k 
../../../../bin/krun --backend java test.simple > sample_outp

The trace cell holds the concrete execution trace, which is a list of integers representing rule ids.
The meta cell contains mappings from integers to locations in the K definition file. For example 1 is mapped to location (384,3,388,45) in the file mentioned. If a rule has some attributes like function, those also appear in the mapping, see 100 -> ... Notice that the trace tracks also contains rules from the k builtins files, e.g., rule 100, so any rule that applies, from any file, is tracked.

OUTPUT:

&lt; coverage-info &gt;
    &lt;trace&gt;
        ListItem(37)
        ListItem(1)
        ListItem(37)
        ListItem(469)
        ListItem(383)
  ......
&lt;meta&gt;
        0 |->
          "[ filename(/home/gyori/play/k/samples/java_rewrite_engine/simple/untyped/simple-untyped.k),  location((384,3,388,45))]"
        1 |->
          "[ filename(/home/gyori/play/k/samples/java_rewrite_engine/simple/untyped/simple-untyped.k),  location((410,3,418,17))]"
        10 |->
          "[ filename(/home/gyori/play/k/samples/java_rewrite_engine/simple/untyped/simple-untyped.k),  location((550,3,550,36))]"
        100 |->
          "[ predicate(),  filename(/home/gyori/play/k/include/builtins/symbolic-k.k),  location((153,3,157,13)),  function()]"
...

**Comment by dwightguth** [comment]
Okay, you need to resolve the conflicts before you merge this. One of the things you need to do, for example, is move the generateTraces flag into KompileOptions. But once all that is taken care of, this should be mergeable.

**Comment by alexgyori** [comment]
Sorry, it's unclear what I should do. I cannot do the merge myself since I do not have permissions.
Could you please be more specific wrt what else I need to do?

**Comment by dwightguth** [comment]
I mean you have merge conflicts. You have to resolve them in your fork before I can merge this myself.

**Comment by cos** [comment]
Unfortunately, it seems like this won't get merged, especially considering the extensive changes in the meantime.

**Pull request closed without merging**
