### PR TITLE
sort-ordered bracket selection

### PR DESCRIPTION
**Pull request by cos**
@grosu, @laurayuwen, this is a fix for unparsing brackets.

The algorithms for unparsing with brackets seems quite decent. The only problem was that it selected a bracket randomly among those available for a sort (including from supersorts). The only change here is that we're now selecting the most specific bracket.

### CODE REVIEW

**Comment by cos** [comment]
note that the PR targets the lambdaAllLessons branch, not master

**Comment by laurayuwen** [comment]
The result looks good to me, thanks @cos .

**Comment by grosu** [comment]
Perfect!  Merging.

Eventually, we are going to probably have attributes for unparsing specifically.  But hopefully we'll have K implemented in K by then.

**Comment by grosu** [comment]
So @laurayuwen , we are now ready for your lambdaAllLessons.  Probably you need to first make a PR on the solution display thing, so when we merge, we have a minimal diff to 3.6.

**Pull request merged**
