### PR TITLE
separated Cell2DataStructures to Java-backend-specific version and non-b...

### PR DESCRIPTION
**Pull request by yilongli**
...ackend-specific version

@dwightguth please review

### CODE REVIEW

**Comment by yilongli** [comment]
@andreistefanescu I have no idea why it also solves your pending problem about printing cell map and cell list... Any idea?

**Comment by andreistefanescu** [comment]
Are you sure the rules are properly transformed? The examples work with cells as well, but the output would be formatted with cells.

**Comment by yilongli** [comment]
Alright, I think I have figured out the problem. This pull request doesn't solve the existing problem about printing cell map and cell list. I made a mistake earlier since I didn't realize Andrei also used this pass to deal with things related to the prover. Therefore, the maude backend doesn't properly transform the rule but somehow still get something looks correct. I have fixed the problem and reverted the output files.

**Comment by yilongli** [comment]
@dwightguth @andreistefanescu please review

**Comment by dwightguth** [comment]
lgtm. @andreistefanescu merge if you are happy.

**Pull request merged**
