### PR TITLE
Eliminate tabs from source file.

### PR DESCRIPTION
**Pull request by paulp**
Without this, "ant test" fails with

```
checkstyle:
[checkstyle] Running Checkstyle 5.7 on 701 files
[checkstyle] AbstractMatcher.java:15:1: File contains tab characters
  (this is the first instance).
```

### CODE REVIEW

**Comment by paulp** [comment]
May I suggest that if checkstyle is going to fail the build, the tests need to be run on pull requests before merging. I know most projects are broken most of the time but I have higher hopes for a correctness-oriented project like this one. Travis has made it crazy-easy to have your tests run on every push (including pull requests) too: https://travis-ci.org/

**Comment by dwightguth** [comment]
I'm sorry about this. We are changing some of our developer workflows and this slipped through the cracks.

May I ask why you're running ant test? If you just want to compile the project, you can just run "ant", and "ant test" is primarily intended for use by K framework developers.

**Comment by paulp** [comment]
When I'm looking to get the sense of a project, I like to exercise a few build targets - especially "test".

**Comment by dwightguth** [comment]
Alright, fair enough. Well we are putting infrastructure in place to run
continuous integration on every pull request, so this shouldn't happen
again. My apologies.

**Comment by paulp** [comment]
Great. Thanks for the speedy resolution.

**Pull request merged**
