### PR TITLE
hotfix for intermittent bug

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by cos** [comment]
@andreistefanescu have a look

**Comment by andreistefanescu** [comment]
lgrm

**Comment by daejunpark** [comment]
@cos could you please explain which bug is fixed, and why?

**Comment by cos** [comment]
There's a bug in the IntelliJ Scala compiler which only pops up in certain interleavings of the Java-Scala mixed compilation. When it pops up, certain invocations of KList cannot find the method anymore. This simplification should fix it. If you've never encountered the bug, don't worry. If it ever pops up again, let me know.

**Pull request merged**
