### PR TITLE
subsorted KResult to KItem instead of K

### PR DESCRIPTION
**Pull request by yilongli**
Fixed https://github.com/kframework/k/issues/718

### CODE REVIEW

**Comment by dwightguth** [comment]
I'm worried about what will happen now if I write something like:

```
rule isKResult(foo ~> bar) => true
```

**Comment by dwightguth** [comment]
Actually I guess that's not any different from what already happens if I say:

```
rule isExp(foo ~> bar) => true
```

Okay, go ahead and merge this if tests pass.

**Comment by grosu** [comment]
That's why I suggested in my previous message that all membership predicates should take KItem arguments.  Radu's parser can enforce that.

Grigore

**Comment by yilongli** [comment]
I created a new issue to keep track of it. https://github.com/kframework/k/issues/729

**Pull request merged**
