### PR TITLE
rename TermContext to State

### PR DESCRIPTION
**Pull request by cos**
just an automated refactoring -- intrusive but should be clean

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: add to whitelist

**Comment by yilongli** [comment]
I am afraid the documentation is going to stay the same.

**Comment by cos** [comment]
ok. hold the merge for now. IntelliJ put in some junk.

**Comment by cos** [comment]
gr... lots of talk about "term context" even though it is not "term" and is not "context"... I'll close this, and try again cleanly. It seems like I'll have to slowly move though hundreds of files to check that the comment/string replacements are correct.... uff

**Pull request closed without merging**
