### PR TITLE
moved isPredicateLabel from MetaK to KLabelConstant

### PR DESCRIPTION
**Pull request by traiansf**
@dwightguth: is this what you proposed?

### CODE REVIEW

**Comment by dwightguth** [comment]
Looks good, my only question is, is it correct to assume that all klabels that start with "is" are predicates? Will we have any kind of odd behavior if for example the user specifies a klabel "issue"?

**Comment by traiansf** [comment]
Not entirely sure about this.... but the original assumption about this was that regular users will use concrete syntax (which prefixes labels with ') while more advanced users should be aware of the issue.  But I agree in principle we should be more careful here.

**Comment by dwightguth** [comment]
Okay. I will approve this if you take the opportunity to make sure that this piece of information is in the k manual.

**Comment by grosu** [comment]
This is a good opportunity to remind everybody about this file:

  https://github.com/kframework/k/blob/master/documentation/to-be-processed.txt

which is currently supposed to collect items that we need to eventually discuss in the manual.  So for now we can assume that something "is in the k manual" if it is listed as an item in this file.

**Comment by traiansf** [comment]
@dwightguth: would this be satisfactory?

**Comment by dwightguth** [comment]
lgtm. Can someone else who works with kompile weigh in to make sure they understand the change?

**Comment by radumereuta** [comment]
lgtm. I think we agreed that only Dwight will merge the pull requests, so I won't do it for now.

**Pull request merged**
