### PR TITLE
LatexFilter: pretty-printing the latex output

### PR DESCRIPTION
**Pull request by denis-bogdanas**

### CODE REVIEW

**Comment by denis-bogdanas** [comment]
@traiansf please review my pull request

**Comment by dwightguth** [comment]
Jenkins: add to whitelist

**Comment by dwightguth** [comment]
Is it possible we could use the Indenter class for this?

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by traiansf** [comment]
looks good to me;  however, if there is some class which would help separate concerns here (like the Indented @dwightguth mentioned), it would be best.

**Comment by denis-bogdanas** [comment]
Ok, will refactor the change and will use Indenter soon.

**Comment by denis-bogdanas** [comment]
Merged.

**Pull request closed without merging**
