### PR TITLE
use tiered compilation to decrease jvm startup cost

### PR DESCRIPTION
**Pull request by dwightguth**
@yilongli please review

### CODE REVIEW

**Comment by yilongli** [comment]
Are you going to also change `kast.bat`, `krun.bat`, etc.?

**Comment by dwightguth** [comment]
Good catch. Will do.

**Comment by yilongli** [comment]
Maybe it's a dumb question, but am I supposed to observe any decrease in the Jenkins build time?

**Comment by dwightguth** [comment]
It's not a dumb question. I'm looking into it. Whenever I try it on my local machine, I see decreases in wall time, but they're not replicable when I run Jenkins. Something further needs tuning I believe.

**Comment by dwightguth** [comment]
After playing around with it some, I've concluded the reason we don't see speedups in ktest is that ktest is currently running on jenkins using 12 threads, but the test suite becomes cpu bound around only 4 or 5 threads. After that point, adding new threads does not decrease wall time, it only increases user time as threads wait to be scheduled. The change in question decreases the cost of running kompile and krun as a single process, but it does not appreciably decrease the load on the cpu, because it relies primarily for its speedup on JVM daemon threads performing compilation and profiling. So when all CPUs are at 100% utilization, the code does not actually run any faster.-

Can I merge this? The speedup from this diff is actually very appreciable.

**Comment by yilongli** [comment]
Yes, please merge if all the tests pass.

**Pull request merged**
