### PR TITLE
separate java backend out into separate maven module / k plugin

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
@cos @yilongli please review. I will fix merge conflicts once you are satisfied with the diff, because otherwise I will spend forever fixing the conflicts every time someone merges a pull request.

**Comment by yilongli** [comment]
Are these directories still necessary in .gitignore?

```
samples/test/
release/
target/
```

**Comment by yilongli** [comment]
I haven't tried this out but it looks good to me.

**Comment by dwightguth** [comment]
Wow, I am completely and utterly baffled by this error. It looks like something went horrifically wrong with Java deserialization because it's trying to assign entirely the wrong class to a field. I am going to try fixing the confilcts and running it again.

**Comment by cos** [comment]
looks good.

**Pull request merged**
