### PR TITLE
Updated definitions in 5_typed

### PR DESCRIPTION
**Pull request by grosu**
All definitions in tutorial/1_k/5_typed kompile now, but there seem to be some bugs in the fixes that @traiansf made and thus ktest does not pass the tests.  Nevertheless, all changes here were quite mechanical, so there should be absolutely no problem once unification.k and/or substitution.k get fixed.  For that reason, I made this into a pull request.

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by grosu** [comment]
@traiansf thanks for the fix.  That made everything up to and including lesson_4 to pass.  However, there are still several tests which fail, in lesson_5 and lesson_9:

```
fslwork$ pwd
/home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_5
fslwork$ '/home/grosu/github.grosu/k/bin/krun' '/home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_4/tests/letrec.lambda' '--search' '--pattern' '<k> V:K </k>' '--directory' '/home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_5'
Search results:

Solution 1:
V:K -->
(lambda f . f) ~> (HOLE (mu f . (lambda x . 3)))
fslwork$ more ../lesson_4/tests/letrec.lambda.out 
Search results:

Solution 1:
V:K -->
#symType(3) -> int

fslwork$ cd ../lesson_9
fslwork$ '/home/grosu/github.grosu/k/bin/krun' '/home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_4/tests/tricky-5.lambda' '--search' '--pattern' '<k> V:K </k>' '--directory' '/home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_9'
Search results:

Solution 1:
V:K -->
(((int) -> #symType(4)) -> (#symType(5) -> #symType(6)))
fslwork$ more tests/tricky-5.lambda.out 
Search results:

Solution 1:
V:K -->
(int -> #symType(4)) -> (int -> #symType(4))
```

These seem to fail for different reasons.

**Comment by traiansf** [comment]
I'll look into that, too

2014-06-28 18:07 GMT+03:00 Grigore Rosu notifications@github.com:

**Comment by grosu** [comment]
Everything works now in 5_types, but this should be merged after #690.

**Comment by traiansf** [comment]
Jenkins: test this please

**Pull request merged**
