### PR TITLE
added support for heap patterns for heaps represented with cells

### PR DESCRIPTION
**Pull request by andreistefanescu**

### CODE REVIEW

**Comment by andreistefanescu** [comment]
@yilongli please review

**Comment by yilongli** [comment]
lgtm

**Comment by dwightguth** [comment]
Go ahead and merge this if tests pass, but we really need to explore our options for refactoring the way we treat with bags. This pull request feels like a giant hack to me. We need the new kast though...

**Comment by radumereuta** [comment]
When this passes, please merge and trigger the build for #698.

**Comment by andreistefanescu** [comment]
@dwightguth it is what it is on the given timeframe. If you have better suggestions on how to use my time, I'm all ears.

**Comment by dwightguth** [comment]
No, I agree, there's nothing we can do now. As I said, we need the new kast.

**Pull request merged**
