### PR TITLE
fixing-issue#709

### PR DESCRIPTION
**Pull request by yilongli**
@dwightguth please review

### CODE REVIEW

**Comment by andreistefanescu** [comment]
==List and =/=List are deprecated. Use ==K and =/=K instead.

**Comment by yilongli** [comment]
Right, I forgot this. I guess I should also remove the declaration of ==List as well?

**Comment by andreistefanescu** [comment]
Yes. Plese remove ==Map and == Set as well.

**Comment by yilongli** [comment]
done please review again @andreistefanescu @dwightguth

**Comment by andreistefanescu** [comment]
Looks good. @traiansf please take a look and see if this is correct for the Maude backend.

**Comment by traiansf** [comment]
Looks ok, although I don't understand why samples/imp-hoare/imp.k had to be completely reformatted.

**Pull request merged**
