### PR TITLE
allow unparsing tokens with no productions

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by radumereuta** [comment]
Is this part of an issue? Why is this needed?
I understand that this is possible, but usually if you need to unparse without a production, then something may be wrong somewhere. You could hide other issues by doing this.

**Comment by cos** [comment]
@radumereuta, yes, but this is as wrong now as it was before. What you would really want here is to throw an error in such cases, not go to the meta level without explanation.

This PR does not solve a problem in the code but in a definition -- see the backlinked issue. I don't know exactly what would be the clean fix for that module problem -- it's a non-obvious one.

**Comment by laurayuwen** [comment]
but @cos , I actually end up with 

```
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
yuwen2@yuwen2-HP-Z220-CMT-Workstation:~/k/k-distribution/tutorial/2_languages/4_logik/basic$ krun tests/fact-5.logik --debug
java.util.NoSuchElementException: key not found: MetaVariable
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:59)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:59)
```

**Comment by cos** [comment]
@laurayuwen, could you give me more of the stack trace?

**Comment by laurayuwen** [comment]
```
java.util.NoSuchElementException: key not found: MetaVariable
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:59)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:59)
    at org.kframework.unparser.KOREToTreeNodes$.apply(KOREToTreeNodes.scala:18)
    at org.kframework.unparser.KOREToTreeNodes$$anonfun$apply$2.apply(KOREToTreeNodes.scala:21)
    at org.kframework.unparser.KOREToTreeNodes$$anonfun$apply$2.apply(KOREToTreeNodes.scala:21)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.Iterator$class.foreach(Iterator.scala:742)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.kframework.unparser.KOREToTreeNodes$.apply(KOREToTreeNodes.scala:21)
    at org.kframework.unparser.KOREToTreeNodes$$anonfun$apply$2.apply(KOREToTreeNodes.scala:21)
    at org.kframework.unparser.KOREToTreeNodes$$anonfun$apply$2.apply(KOREToTreeNodes.scala:21)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.Iterator$class.foreach(Iterator.scala:742)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.kframework.unparser.KOREToTreeNodes$.apply(KOREToTreeNodes.scala:21)
    at org.kframework.unparser.KOREToTreeNodes$$anonfun$apply$2.apply(KOREToTreeNodes.scala:21)
    at org.kframework.unparser.KOREToTreeNodes$$anonfun$apply$2.apply(KOREToTreeNodes.scala:21)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.Iterator$class.foreach(Iterator.scala:742)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.kframework.unparser.KOREToTreeNodes$.apply(KOREToTreeNodes.scala:21)
    at org.kframework.unparser.KOREToTreeNodes.apply(KOREToTreeNodes.scala)
    at org.kframework.krun.KRun.unparseTerm(KRun.java:356)
    at org.kframework.krun.KRun.prettyPrint(KRun.java:229)
    at org.kframework.krun.KRun.run(KRun.java:89)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:97)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
```

**Comment by cos** [comment]
@laurayuwen, try it now

**Comment by laurayuwen** [comment]
OK, now I have

```
Search results:

Solution 1:
Solution:Map -->
X:Term |-> john
```

**Pull request merged**
