### PR TITLE
add brandon's compiler patch

### PR DESCRIPTION
**Pull request by dwightguth**
@bmmoore please review

Let me know if you have a better suggestion for where to store the patch file.

@pdaian FYI. If we go this route and put the patch file here it's going to be very important that it doesn't get deleted or things will break.

### CODE REVIEW

**Comment by bmmoore** [comment]
Try using opam variables - the interpolation syntax like `%{lib}` should also work in the patch name. There's nothing quite as nice as a variable specifically for the current repo, but we could probably get by hardcoding the "k" name into something like `%{root}/repo/k/compilers/4.03.0/4.03.0+k/files/compiler-patch.patch`, if you add the patch at `files/compiler-patch.patch` under the switch definition in the k repo.

https://opam.ocaml.org/doc/Manual.html#Variables

Please investigate this first, before we host the patch ourselves. Hosting the patch is fine if there are no other options, but making sure it stays up will be annoying.

**Comment by bmmoore** [comment]
k-configure-opam-dev is not marked executable

**Comment by dwightguth** [comment]
It actually doesn't have to be because the mode is set by the assembly plugin and the script isn't intended to be run out of the src/main/scripts dir.

**Comment by bmmoore** [comment]
Ok, but it's still a bit odd that the scripts differ on that.
I do see a this message in the middle of running the scripts:

```
[ERROR] k is already a remote repository
```

but it still updated the files and built the compiler ok.
(I didn't see an obvious option to suppress that message)
Looks good enough.

**Pull request merged**
