### PR TITLE
revert #1962 because of failure to correctly print errors in non comp…

### PR DESCRIPTION
**Pull request by dwightguth**
…iling definitions

@radumereuta please take a look but do not merge yet, I still have to test the changes to kdep.

### CODE REVIEW

**Comment by radumereuta** [comment]
lgtm. Tried it on my machine and now works.
#2023 should be fixed now.

**Comment by dwightguth** [comment]
@cos FYI this was your commit it's now your responsibility to fix the issue and remerge the code as well as to make sure that the merge conflicts that I created in this diff get resolved in favor of all the right things moving forward.

To summarize the issue, your code does not correctly crash the tool with an error in all cases when a parsing error occurs, which caused rules to mysteriously vanish from the definition without it being clear why.

**Comment by cos** [comment]
no @dwightguth, this is not ok! That PR was essentially doing part of the refactoring you have been postponing months. If you look at the before code, most of it is yours. It is also code that the kdoc branch depends on. If you do not like, please do the refactoring yourself asap, and also merge with the kdoc-with-meta branch. 

Also, it is not ok to revert a very large PR for the sake of fixing a small error propagation issue.

**Comment by dwightguth** [comment]
Yes I'm quite aware most of the code is mine, however, before this diff the tool worked and after it it did not work. There were multiple people whose progress was broken and blocked because this was not working. I opted to implement the fastest possible fix which was to isolate the code that was defective and revert it. This is fairly typical software workflow methodology when dealing with major regressions. It would have taken significantly longer for me to try to fix the regression myself and throughout that time the tool would have been in a broken state where literally nobody could safely be doing any K-language development using the latest version of K.

If you're upset that the diff is too large for the amount of code that was faulty, make smaller diffs, and test them better. If on the other hand it really is trivial to fix this error, well, it shouldn't take you much time to fix then.

**Comment by cos** [comment]
@dwightguth, if the issue is that extensive, why did it escape Jenkins? Oh, because none of the caching code that you have introduced and I partially refactored has any tests? 

This is not production code, nobody would have been greatly affected if you would have given me a heads up and allowed me to have a look. @radumereuta, you merged this very large PR at two hours after @dwightguth made it, and nobody mentioned me. Would it have been that hard to ask me if it's ok and give me a couple of hours before merging? It is common courtesy. 

Finally, @dwightguth, I cannot make smaller PRs when the refactoring fixes one large mess.

**Comment by dwightguth** [comment]
1 blocked person is better than 2 blocked people. I'm sorry I didn't let you know this was happening before I merged the revert. That's my bad, I will try to do better in the future.

That said, yes, it is that hard to give you a couple hours in this case. 2 hours while you fix this is actually 6 hours because it's blocking a total of 3 people. That's not an insignificant amount of lost productivity. After this was merged only one person was blocked. That's why it was done as quickly as possible (in 12 minutes), so that instead of losing 6 hours we only lose 2 hours and 24 minutes.

**Comment by radumereuta** [comment]
@cos why are you taking this personal?
I spent 2-3 hours tonight trying to understand what was going on with K, and couldn't figure it out.
I searched out for @dwightguth maybe he could help. After that we had to bisect and search where the problem was. This is not something that we can wait for you to figure out when you are not in the office.

@dwightguth took the correct decision in this case, especially since we couldn't trust the tests in this case, since it slipped through. This PR needs another closer look, and some extra tests this time.

If there is something to be taken from this, is that we DESPERATELY need negative tests. Just to say that definition `X` should fail with error message `Y`.

**Comment by cos** [comment]
> I spent 2-3 hours tonight trying to understand what was going on with K, and couldn't figure it out.
> I searched out for @dwightguth maybe he could help. After that we had to bisect and search where the problem was. 

@radumereuta, I have spent 2-3 days figuring out how to split that code apart, refactoring it, and getting it merged -- I would have taken significantly less to rewrite it but then I would have had to rewrite also all the tentacles that were already depending on it.

The trickiest part of that code was caching as it was entangled with the functionality. The caching part, in the original code, did not have unit tests and that is the reason the PR passed Jenkins and failed afterwards.

Regarding urgency, that PR has been merged for 4 days and hell didn't brake loose. As I understand, the problem was that errors were reported incorrectly when something came from the cache, while the positive cases were still working. Who was truly blocked? I doubt this kind of rush was warranted. We're talking about `master`, not `stable`/`production` after all. As I see you're following with a revert of the AC branch. This is becoming non-trivial. All of this could have waited for another couple of hours. 

@radumereuta, regarding not being in the office, even when traveling I have quite a good response time -- so let's not go there. Furthermore, you know how to get a hold of me on Google Hangouts, phone, etc. A simple message "hey we have this problem with your PR and we're going to revert it, could you have a look if you have a better solution?" would have worked. I only heard from you after the PR was already merged.

Regarding the timeline, the PR was never marked `ready-for-review`, I was not mentioned at all in it, and you merged it in 12 minutes after @dwightguth proposed it. Actually,@dwightguth said " please take a look but do not merge yet, I still have to test the changes to kdep", but maybe he gave you an informal ok afterwards.

> @cos why are you taking this personal?

@radumereuta, I'm not taking this "personal". I take this as a disregard of both process and common courtesy which negatively affects my work. As I do care quite a bit about my work, I take this, not personally, but much worse, seriously. 

And yes, there would have been alternate solutions: e.g., have a separate branch for anybody affected by this. Would this have worked for a couple of hours?

> If there is something to be taken from this, is that we DESPERATELY need negative tests. Just to say that definition X should fail with error message Y.

Great. Our framework is supposed to be usable programatically. So why the desperation? Simply add a unit test that tests the negative side. If you cannot do it easily, it means we have a problem. And yes, I know you cannot do it very easily. You'll have to set up a bunch of irrelevant stuff just to get close to it. This is what the PR that was reverted was going towards. Having all features available individually programmatically so that a negative test, or any other simple use of the framework, isn't an exercise in code acrobatics.

**Comment by cos** [comment]
@dwightguth, thank you for acknowledging this. Let's try to move this forward. 

@radumereuta, could you branch just before this PR and try to add a negative unit test for the problem you encountered? If you cannot do it as a unit test, look at how @daejunpark added negative ktests recently. I will look into it and try to fix it tomorrow at 11am central.

**Pull request merged**
