### PR TITLE
Fixing issue #428.

### PR DESCRIPTION
**Pull request by radumereuta**
- errors found in VariableTypeInference were reported immediately instead being thrown further.
- fixed some typos.

### CODE REVIEW

**Comment by radumereuta** [comment]
@dwightguth I've tested everything about the parser, and it works as expected. The only things that I don't understand, are left in Krun. I don't feel comfortable enough to work on krun. Can you have a look, and fix the test?

I found that are various inconsistencies when calling krun with --parser.

**Comment by radumereuta** [comment]
This is actually really strange. The tests pass on jenkins. It must be something wrong with my windows machine then.

**Comment by dwightguth** [comment]
If I had to hazard a guess I'd say it's probably because the successful execution of this test depends on environment variables, and Windows is messing it up somehow. I suggest you try to create a minimal reproducible example and then create an issue. I may not have time to get to it right away however.

This looks good to me right now, so I am merging this.

**Comment by radumereuta** [comment]
You can test it with the example I just added. Ktest fails for it.

**Comment by dwightguth** [comment]
If you have an example that breaks the test, can you re-create the pull
request containing that example? As you can see, since it worked when you
ran ktest, I assumed it was a windows-specific thing and went ahead and
merged.

**Comment by radumereuta** [comment]
I wanted to say, that if you run ktest on windows for this example, it fails. Although it shouldn't.
So the negative test should be for you to run it on windows.

**Comment by dwightguth** [comment]
Per my discussion with Radu, fixing this would require a significant
overhaul of the internal vs. external parsing framework. it's on my todo
list, but way low, after a bunch of other stuff. You can make an issue and
assign it to me though if you want.

**Pull request merged**
