### PR TITLE
fix unicode support in new parser

### PR DESCRIPTION
**Pull request by dwightguth**
@radumereuta please review

### CODE REVIEW

**Comment by radumereuta** [comment]
I think this deserves a more complex test that includes outer parsing, and calling the new parser for programs on something that contains unicode characters.

**Comment by dwightguth** [comment]
@radumereuta please review

**Comment by radumereuta** [comment]
lgtm, merge if tests pass.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
