### PR TITLE
remove "isDefaultPattern" field

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
Seems to have segfaulted. This is the z3 error we've seen before. @andreistefanescu , do you know if the z3 guys have fixed this issue yet? It'd be good to take care of once and for all if we can.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@yilongli please review

**Comment by yilongli** [comment]
lgtm

**Pull request merged**
