### PR TITLE
Fix i549

### PR DESCRIPTION
**Pull request by radumereuta**

### CODE REVIEW

**Comment by radumereuta** [comment]
@dwightguth please review.

**Comment by dwightguth** [comment]
So, this is good, but not quite good enough. I ran into other cases where a KApp had arity 1 and its representation in Java was not a KList. For example:

```
syntax KItem ::= "foo"

rule isKResult(foo) => true
```

If this parses as a KApp, it should contain a child which is a KList of length 1 also.

**Comment by radumereuta** [comment]
So, is it ok if I verify only if the child node is not of sort KList?
I think it solves the problem in general.

**Comment by dwightguth** [comment]
That should work, I think, yes.

**Pull request merged**
