### PR TITLE
[ktest] bring back location to nagative test

### PR DESCRIPTION
**Pull request by daejunpark**

### CODE REVIEW

**Comment by daejunpark** [comment]
fix #1984

**Comment by radumereuta** [comment]
lgtm

**Comment by daejunpark** [comment]
@radumereuta I'll make a separate PR for the individual `<test>` issue. This is only for brining the location information back. Please merge if you're happy with it.

**Comment by radumereuta** [comment]
Cool. It's not urgent, but if it doesn't take you a lot of time, you should do it, since it may save us time in the future trying to debug.

**Pull request merged**
