### PR TITLE
Fix java backend

### PR DESCRIPTION
**Pull request by yilongli**
several important fix for the Java backend in order to run/prove list_reverse.cil.c

@andreistefanescu  please review

### CODE REVIEW

**Comment by yilongli** [comment]
It's surprising that I can still find quite a few bugs in the Java backend in one night. I am still working on the last one. I will add regression tests when I am done.

**Comment by andreistefanescu** [comment]
lgtm

**Comment by yilongli** [comment]
@andreistefanescu added two more commits, please re-review

**Comment by andreistefanescu** [comment]
lgtm

**Pull request merged**
