### PR TITLE
Several performance optimizations to OCAML backend

### PR DESCRIPTION
**Pull request by dwightguth**
@bmmoore please review

### CODE REVIEW

**Comment by bmmoore** [comment]
Where is the `--exit-code` flag defined and documented? I see text for a message saying it's required, but not how it's actually passed in.

**Comment by dwightguth** [comment]
I just added a paragraph to the manual.

**Comment by dwightguth** [comment]
It's defined in KRunOptions though.

**Comment by bmmoore** [comment]
Ok. The rest of the code looks good, as long as you're sure the options and invocation are correctly handled. I'm in the middle of a ktest invocation so I haven't been able to compile and try it myself yet.

**Pull request merged**
