### PR TITLE
Em/fix location info

### PR DESCRIPTION
**Pull request by daejunpark**

### CODE REVIEW

**Comment by daejunpark** [comment]
@cos please review

**Comment by daejunpark** [comment]
@cos just let me know if you're happy, but do NOT merge this. I have to rebase this on master before merging.

**Comment by daejunpark** [comment]
should be merged after #2043

**Comment by cos** [comment]
looks good. removed the "ready-for-review" flag so that I don't merge it by mistake.

**Comment by daejunpark** [comment]
This can be merged now, because #2043 has been merged.

**Comment by cos** [comment]
Jenkins: test this please

**Pull request merged**
