### PR TITLE
stop variable type inference from inferring variables as KList

### PR DESCRIPTION
**Pull request by dwightguth**
@bmmoore please review

### CODE REVIEW

**Comment by radumereuta** [comment]
lgtm, but what is the reason for this? I don't see any reference to an issue or a discussion.

**Comment by dwightguth** [comment]
It's a bug that arises when you write the following rule in the java backend:

```
syntax Int ::= foo(Int) [function]

rule `foo`(_) => 0 [owise]
```

**Comment by bmmoore** [comment]
Code is fine, but please add a comment explaining the signficance of the tests - that sorts above K or at and below KBott are assumed to only come from the K-in-K grammar from kast.k.

**Comment by radumereuta** [comment]
Also, are there any unit tests for this?

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by bmmoore** [comment]
lgtm

**Pull request merged**
