### PR TITLE
Parser phases

### PR DESCRIPTION
**Pull request by adamsmd**
Added a phase distinction in error messages between between the inner and outer parsers.

### CODE REVIEW

**Comment by radumereuta** [comment]
test this please

**Comment by adamsmd** [comment]
Why did Jenkins send this message?  I don't understand it.  Did I do 
something wrong with the pull request?

**Comment by dwightguth** [comment]
It's a little temperamental sometimes, in terms of whether or not it thinks you are a member of the group of individuals who is allowed to submit build requests. Some kind of bug. I've just been adding people to the whitelist when it happens and it fixes the issue.

**Comment by dwightguth** [comment]
test this please

**Comment by dwightguth** [comment]
if Radu approves and the tests pass, you can merge this.

**Comment by radumereuta** [comment]
lgtm, merging

**Pull request merged**
