### PR TITLE
fix caching issue + refactoring

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by radumereuta** [comment]
Updated #2039 with the description of another caching related bug. Please fix it before merging.

**Comment by dwightguth** [comment]
It's more urgent in this case that we don't call saveCaches more than once because that causes a significant performance penalty. Can you please go through this and make sure it's only called once on each code path while at the same time ensuring that it's always called after completion of parsing?

**Comment by dwightguth** [comment]
@radumereuta can we merge this if it fixes the issue where rules are not cached at all? I would really like to go back to having second runs of  compiling the C semantics not take 6 minutes.

**Comment by cos** [comment]
@dwightguth, the cache saving is only invoked once now.

**Comment by radumereuta** [comment]
I haven't spent too much time trying to understand the original refactoring, so @dwightguth if you are happy with the PR, go ahead and merge. I tested it and it appears to report the correct number of cached rules.

**Comment by radumereuta** [comment]
Tested again, after the latest fix, and the first run on an empty definition shows [108/108] parsed rules and 3 seconds. The second time [0/180], and 1.9 seconds.
I guess it may be fixed.

**Pull request merged**
