### PR TITLE
fixing issue 825

### PR DESCRIPTION
**Pull request by yilongli**
fixing https://github.com/kframework/k/issues/825

### CODE REVIEW

**Comment by yilongli** [comment]
@andreistefanescu please review

**Comment by andreistefanescu** [comment]
Looks good. Please add the example provided by @liyili2 as a unit test.

**Comment by yilongli** [comment]
But the error shown in the example is far from the root cause, which is the visitor implementation. I don't think including that example would not be very useful in the future. Instead, if we always use `baseTerms()` instead of `collectionPatterns()/Functions()/Variables()` separately, we won't likely have this kind of issue anymore.

**Comment by dwightguth** [comment]
@andreistefanescu I'm persuaded by Yilong's logic. Are you okay if I merge this?

**Comment by andreistefanescu** [comment]
agreed

**Pull request merged**
