### PR TITLE
add ecdsa public key recovery function to KRYTPO module

### PR DESCRIPTION
**Pull request by dwightguth**

### CODE REVIEW

**Comment by dwightguth** [comment]
Please don't merge this yet, it's computing incorrect senders. I will investigate further tomorrow.

**Comment by dwightguth** [comment]
Okay, this is ready for review. I tested with the evm semantics. There seems to be another bug somewhere but it's unrelated to the crypto built-in. I'll investigate tomorrow.

**Review by msaxena2 — COMMENTED** [review]
@dwightguth Could you add a test to BuiltinCryptoOperationsTest.java for this?

**Comment by dwightguth** [comment]
I can do that tomorrow, yeah, but I'm not entirely sure what good it will do because I will have to derive the test input and outputs from running the test code in a debugger and inspecting the outputs, in which case I'm not really testing anything. I can tell you that the code correctly computes the senders of transactions in the evm semantics though.

**Comment by msaxena2** [comment]
@dwightguth Is it possible to find a standard set of values that we can test against? Like some documentation with an example online?

**Comment by dwightguth** [comment]
I'll look tomorrow, maybe ethereumj has tests.

**Comment by dwightguth** [comment]
@msaxena2 I added a test for public key recovery by manually translating the test inputs and outputs for a test that came from ethereumj into K. Can we get this merged now that it's tested and documented?

**Comment by msaxena2** [comment]
@dwightguth Lgtm. Will merge as soon as tests pass.

**Review by msaxena2 — APPROVED** [review]

**Pull request merged**
