### PR TITLE
Started to remove #String from the front end.

### LINKED ISSUE #789: Error of checking an element in the keys of a map when I use C options to input a configuration
I spent two days to understand this problem really. If I have this set of rules:

```
module TEST

   configuration  
<T multiplicity="?">   
    <k color="green" multiplicity="?"> 
          loadMergeObj(
               unwrapObj($OBJ1:Bag), 
               unwrapObj($OBJ2:Bag))
          ~> ($PGM:K)
     </k>
<options> $OPTIONS:Set </options>
</T>
<global>
<tu>
<env>.Map</env>
</tu>
</global>

     syntax Bag ::= unwrapObj(Bag) [function]

     rule unwrapObj(<generatedTop>... 
               <global> G:Bag </global> 
          ...</generatedTop>) 
          => <global> G </global>

     rule unwrapObj(.Bag) => .Bag

     syntax KItem ::= loadMergeObj(Bag , Bag) [function]
     syntax KItem ::= loadObj(Bag)

     rule loadMergeObj(A:Bag , .Bag) => loadObj(A)
     rule loadMergeObj(.Bag , A:Bag) => loadObj(A)

     rule <k> loadObj(<global> G:Bag </global>) => .K ...</k>
          <global> (_:Bag => G) </global>
          requires (G =/=Bag .Bag)
          [structural]

     rule loadObj(.Bag) => .K
          [structural]

   syntax KItem ::= "start" | "end"

   syntax CId ::= Identifier(String)

   syntax Map ::= "builtins" [function]

   rule builtins =>
          "__debug" |-> 1
          "__fslCloseFile" |-> 1
          "__fslFGetC" |-> 2
          "__fslOpenFile" |-> 1
          "__fslPutc" |-> 1
          "__va_copy" |-> 1
          "__va_end" |-> 1
          "__va_inc" |-> 1
          "__va_start" |-> 1
          "abort" |-> 1
          "asin" |-> 1
          "atan" |-> 1
          "atan2" |-> 1
          "calloc" |-> 1
          "cos" |-> 1
          "exit" |-> 1
          "exp" |-> 1
          "floor" |-> 1
          "fmod" |-> 1
          "free" |-> 1
          "getchar" |-> 1
          "log" |-> 1
          "longjmp" |-> 1
          "malloc" |-> 1
          "mtx_init" |-> 1
          "mtx_lock" |-> 1
          "mtx_unlock" |-> 1
          "printf" |-> 1
          "putchar" |-> 1
          "rand" |-> 2
          "realloc" |-> 2
          "setjmp" |-> 2
          "sin" |-> 2
          "snprintf" |-> 2
          "sprintf" |-> 2
          "sqrt" |-> 3
          "srand" |-> 3
          "strcpy" |-> 3
          "tan" |-> 3
          "thrd_create" |-> 3
          "thrd_current" |-> 3
          "thrd_join" |-> 3
          "time" |-> 3

   syntax KItem ::= addBuiltins(Map) | addBuiltin(CId,Int)

   rule addBuiltins(.Map) => .K

   rule <k> (.K => addBuiltin(Identifier(C),I)) ~> addBuiltins((C:String |-> I:Int => .Map) S:Map)  
    ...</k>

   rule <k> addBuiltin(C:CId,I:Int) => .K ...</k>
        <env>... (.Map => C |-> I) ...</env>

   rule <T><k> true </k><options>S:Set</options> </T> => . [structural]

   rule start => addBuiltins(builtins) ~> end
   rule <k> end => (Identifier("atan") in keys(M)) ...</k><env>M:Map</env>

endmodule
```

and I run the program "start" by the following command:

```
krun --smt none --output "pretty" --output-file "ctype.pretty.o" -cOPTIONS="(SetItem(1) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" a.test
```

I will get a correct result as:

```
<global>
    <tu>
        <env>
            Identifier ( "__debug" ) |-> 1 Identifier ( "__fslCloseFile" ) |->
               1 Identifier ( "__fslFGetC" ) |-> 2 Identifier ( 
              "__fslOpenFile" ) |-> 1 Identifier ( "__fslPutc" ) |-> 1 
              Identifier ( "__va_copy" ) |-> 1 Identifier ( "__va_end" ) |-> 1
               Identifier ( "__va_inc" ) |-> 1 Identifier ( "__va_start" ) |->
               1 Identifier ( "abort" ) |-> 1 Identifier ( "asin" ) |-> 1 
              Identifier ( "atan2" ) |-> 1 Identifier ( "atan" ) |-> 1 
              Identifier ( "calloc" ) |-> 1 Identifier ( "cos" ) |-> 1 
              Identifier ( "exit" ) |-> 1 Identifier ( "exp" ) |-> 1 
              Identifier ( "floor" ) |-> 1 Identifier ( "fmod" ) |-> 1 
              Identifier ( "free" ) |-> 1 Identifier ( "getchar" ) |-> 1 
              Identifier ( "log" ) |-> 1 Identifier ( "longjmp" ) |-> 1 
              Identifier ( "malloc" ) |-> 1 Identifier ( "mtx_init" ) |-> 1 
              Identifier ( "mtx_lock" ) |-> 1 Identifier ( "mtx_unlock" ) |-> 
              1 Identifier ( "printf" ) |-> 1 Identifier ( "putchar" ) |-> 1 
              Identifier ( "rand" ) |-> 2 Identifier ( "realloc" ) |-> 2 
              Identifier ( "setjmp" ) |-> 2 Identifier ( "sin" ) |-> 2 
              Identifier ( "snprintf" ) |-> 2 Identifier ( "sprintf" ) |-> 2 
              Identifier ( "sqrt" ) |-> 3 Identifier ( "srand" ) |-> 3 
              Identifier ( "strcpy" ) |-> 3 Identifier ( "tan" ) |-> 3 
              Identifier ( "thrd_create" ) |-> 3 Identifier ( "thrd_current" )
               |-> 3 Identifier ( "thrd_join" ) |-> 3 Identifier ( "time" ) 
              |-> 3
        </env>
    </tu>
</global>
```

because K will evaluate the final boolean expression "(Identifier("atan") in keys(M))" to "true". To show the error, I will need to run the binary version of the command above as:

```
krun --smt none --output "binary" --output-file "ctype.o" -cOPTIONS="(SetItem(1) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" a.test
```

Then, I will run another command as:

```
krun --smt none --output "pretty" --output-file "output.txt" -cOPTIONS="(SetItem(1) .Set)" -cOBJ1=".Bag" -pOBJ2="kast --parser binary" -cOBJ2="ctype.o" b.test
```

This command will input the final configuration above as a binary file "ctype.o" and run the program "end", which is in b.test. However, the Java bacend will incorrectly evaluate the final boolean expression "(Identifier("atan") in keys(M))" to "false". The final configuration of running the program "end" is:

```
<T>
    <k>
        false
    </k>
    <options>
        SetItem ( 1 )
    </options>
</T>
<global>
    <tu>
        <env>
            Identifier ( "__debug" ) |-> 1 Identifier ( "__fslCloseFile" ) |->
               1 Identifier ( "__fslFGetC" ) |-> 2 Identifier ( 
              "__fslOpenFile" ) |-> 1 Identifier ( "__fslPutc" ) |-> 1 
              Identifier ( "__va_copy" ) |-> 1 Identifier ( "__va_end" ) |-> 1
               Identifier ( "__va_inc" ) |-> 1 Identifier ( "__va_start" ) |->
               1 Identifier ( "abort" ) |-> 1 Identifier ( "asin" ) |-> 1 
              Identifier ( "atan2" ) |-> 1 Identifier ( "atan" ) |-> 1 
              Identifier ( "calloc" ) |-> 1 Identifier ( "cos" ) |-> 1 
              Identifier ( "exit" ) |-> 1 Identifier ( "exp" ) |-> 1 
              Identifier ( "floor" ) |-> 1 Identifier ( "fmod" ) |-> 1 
              Identifier ( "free" ) |-> 1 Identifier ( "getchar" ) |-> 1 
              Identifier ( "log" ) |-> 1 Identifier ( "longjmp" ) |-> 1 
              Identifier ( "malloc" ) |-> 1 Identifier ( "mtx_init" ) |-> 1 
              Identifier ( "mtx_lock" ) |-> 1 Identifier ( "mtx_unlock" ) |-> 
              1 Identifier ( "printf" ) |-> 1 Identifier ( "putchar" ) |-> 1 
              Identifier ( "rand" ) |-> 2 Identifier ( "realloc" ) |-> 2 
              Identifier ( "setjmp" ) |-> 2 Identifier ( "sin" ) |-> 2 
              Identifier ( "snprintf" ) |-> 2 Identifier ( "sprintf" ) |-> 2 
              Identifier ( "sqrt" ) |-> 3 Identifier ( "srand" ) |-> 3 
              Identifier ( "strcpy" ) |-> 3 Identifier ( "tan" ) |-> 3 
              Identifier ( "thrd_create" ) |-> 3 Identifier ( "thrd_current" )
               |-> 3 Identifier ( "thrd_join" ) |-> 3 Identifier ( "time" ) 
              |-> 3
        </env>
    </tu>
</global>
```

I expect the final configuration of running program "end" by inputing ctype.o the same as the final configuration as the final configuration by running program "start" through the command:

```
krun --smt none --output "pretty" --output-file "ctype.pretty.o" -cOPTIONS="(SetItem(1) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" a.test
```

### PR DESCRIPTION
**Pull request by radumereuta**
@yilongli I've started this in order to fix #789.
I tried a small example, and it still worked, although I'm pretty sure ktest is going to fail.
I think this should be enough for the front end. If not, then we could meet tomorrow and sort it out.

### CODE REVIEW

**Comment by yilongli** [comment]
I looked into the incorrect outputs given by the Java backend. It turns out that many of the errors are simply due to the broken IO, or more specifically, the `+String` operation. If you set a conditional break point at `KApp.of(Term label, Term... elements)` looking for `label` containing `#String`, you will find stuffs like `#token("#String", "\"Testing Collatz' conjecture up to what number? \"")`. I traced it back to `Token.kAppOf(Element element)`. The attributes of this element is `[filename="cast-1.kool", loc="(15,11,15,60)", sort="#String", value=""Testing Collatz' conjecture up to what number? ""]`. I cannot go further because it seems like a front-end issue.

**Comment by radumereuta** [comment]
I just searched the code, and the only occurrences of #String are in a few files in the backend, related to the maude backend.
I'm not sure exactly how you found that error, but if you need to change something in the front end, go ahead. I can review the code after you manage to make it work again.

**Comment by yilongli** [comment]
OK, I will take a look again when I get a chance.

**Comment by yilongli** [comment]
BTW, there is still `#String` in `builtins/string.k`. Do you think that might be the problem?

**Comment by liyili2** [comment]
What is the status of the change.

**Comment by yilongli** [comment]
This change is going to take a while. I will try to provide a temporary fix to circumvent the problem revealed in https://github.com/kframework/k/issues/789.

**Comment by dwightguth** [comment]
Closing. Please reopen on master

**Pull request closed without merging**
