### PR TITLE
Fix for Issue #720

### PR DESCRIPTION
**Pull request by traiansf**
@dwightguth please review

### CODE REVIEW

**Comment by dwightguth** [comment]
lgtm. merge if tests pass

**Comment by traiansf** [comment]
@dwightguth All tests finally pass, but we are in a merge freeze.  Please merge it after the unfreeze.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@traiansf looks like you need to update your editor settings to take care of whitespace in .k files.

**Comment by traiansf** [comment]
Ok, I'm puzzled.  I'm using a variety of editors, on a Windows machine.  Of course they tend to put windows line endings esp. to newly created files to make them readable through not-so-smart-but-neverhteless-usefull Windows editors like Notepad.  But I sincerely thought that git is taking care of converting between line endings to make everybody happy by keeping the server with one kind of line endings and converting them appropriately on each OS.

Now, w.r.t. trailing whitespace:  I'm mostly using vim for k.  Can't a line be added to the vim configuration for K to automagically remove trailing whitespace when saving?  If so, can somebody who is more proficient with vim configurations do this?

**Comment by radumereuta** [comment]
Git indeed takes care of converting windows line endings to linux when commiting. The problem is that we already had so many windows terminators from SVN, which are being annoying now. I actually support what Dwight is doing right now.

**Comment by traiansf** [comment]
I'm not saying I don't support what he's doing. Just that I need assistance for complying.

**Comment by dwightguth** [comment]
This is what I found on a casual google search. Should give you several options.

http://stackoverflow.com/questions/356126/how-can-you-automatically-remove-trailing-whitespace-in-vim

**Comment by dwightguth** [comment]
As far as git goes, I don't exactly know what it's capable of but I do know that it doesn't seem to be smart enough to stop IDEs from messing with the newline character inappropriately and causing newlines to get inconsistent. I decided to value code base conformity over ease of use on windows, because I don't want to have to worry about misconfigured editors screwing things up.

**Pull request merged**
