### PR TITLE
refactor kast options

### PR DESCRIPTION
**Pull request by dwightguth**
- delete --fast-kast option
- use JCommander for KAST
- remove all but one field in GlobalSettings

@radumereuta please review

### CODE REVIEW

**Comment by radumereuta** [comment]
Ok, lgtm. It seems that you already removed many parts of the fastKast functionality.
Some other things are still left, but I will remove them in a future pull request.

If all tests pass, you can merge from my point of view.

**Comment by radumereuta** [comment]
It failed because the tests/newparser/config.xml calls kast -parser instead of --parser.

**Comment by dwightguth** [comment]
Yeah, I saw. I'll fix it tomorrow morning. Do you want to re-review it
then, or should I just merge it once the tests all pass?

**Comment by radumereuta** [comment]
You can just go ahead and merge when all tests pass.

**Comment by dwightguth** [comment]
@radumereuta I merged the visitors change so can you maybe look at this again after all just to make sure I didn't do anything funny in the merge?

**Pull request merged**
