### PR TITLE
Fun updated

### PR DESCRIPTION
**Pull request by grosu**
FUN also works with unified-builtins2.  The substitution-based definition only needed to change one . into .Map.  That was nice.

### CODE REVIEW

**Comment by dwightguth** [comment]
Looks like you just need to fix output on this one to make the tests pass.

**Comment by grosu** [comment]
Wow, things move fast!  It worked with yesterday's version of unified-builtins2, but now the pretty printer is better.  Cool.  I'm going to fix the output file immediately.

Grigore

**Comment by grosu** [comment]
Done.

@andreistefanescu @traiansf @dwightguth Please revise (should be really easy)

**Comment by andreistefanescu** [comment]
lgtm

**Pull request merged**
