### PR TITLE
Added better error message for when SDF crashes

### PR DESCRIPTION
**Pull request by radumereuta**
to indicate the line number of the rule in question.

@dwightguth please review.

I've added a catch for any type of exception that SDF might throw since I'm the only one interested in them, and replace it with a K localized message to indicate which is the rule that doesn't parse and crashes the parser.

### CODE REVIEW

**Comment by radumereuta** [comment]
@dwightguth please have a look.
The checkstyle is not letting me catch `Exception`, although I think this is a good solution for when SDF crashes with all sorts of problems.
Alternatives?

**Comment by dwightguth** [comment]
The reason for this is that the code as you wrote it is catching KEMException which it should not be doing. You need to decide which specific concrete exceptions you want to catch and or them together. Like so:

```
} catch (IllegalArgumentException | IOException | NullPointerException e) {
  // etc
}
```

**Comment by radumereuta** [comment]
@dwightguth please re-review.
I think I only need `RuntimeException` in this case, so I'm going to try it like this and see how it goes.
Combined with your latest pull request, the error messages should look a lot better now.

**Comment by dwightguth** [comment]
This isn't going to work either. You said you needed to catch OutOfMemoryError and StackOverflowError. Neither of those two are RuntimeExceptions. They inherit from Error which inherits from Throwable. If you want to catch those two errors to print a better error message, be my guest. But we still should not be catching Throwable, Error, Exception, or RuntimeException.

**Comment by radumereuta** [comment]
I don't know exactly how it happens, but the parser actually throws a `RuntimeException` which reports the `OutOfMemoryError`. So my solution will work for now.

**Comment by dwightguth** [comment]
What is the stack trace of the RuntimeException?

**Comment by radumereuta** [comment]
```
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java)
        at org.strategoxt.lang.Context.invokeStrategyCLI(Context.java)
        at org.kframework.parser.concrete.KParser.ParseKConfigString(KParser.java:210)
        at org.kframework.parser.generator.ParseRulesFilter.visit(ParseRulesFilter.java:70)
        at org.kframework.parser.generator.ParseRulesFilter.visit(ParseRulesFilter.java:33)
        at org.kframework.kil.StringSentence.accept(StringSentence.java:36)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
        at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
        at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:300)
        at org.kframework.parser.generator.ParseRulesFilter.visit(ParseRulesFilter.java:52)
        at org.kframework.parser.generator.ParseRulesFilter.visit(ParseRulesFilter.java:33)
        at org.kframework.kil.Module.accept(Module.java:111)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
        at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
        at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:284)
        at org.kframework.kil.Definition.accept(Definition.java:144)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
        at org.kframework.parser.DefinitionLoader.parseDefinition(DefinitionLoader.java:291)
        at org.kframework.parser.DefinitionLoader.loadDefinition(DefinitionLoader.java:119)
        at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:107)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:88)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:43)
        at org.kframework.main.Main.main(Main.java:40)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:441)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:469)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:478)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:469)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:469)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:478)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:478)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:469)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:478)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:478)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:478)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:478)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:469)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:469)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:469)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
        at org.spoofax.jsglr.client.Disambiguator.filterTree(Disambiguator.java:478)
        at org.spoofax.jsglr.client.Disambiguator.filterAmbiguities(Disambiguator.java:820)
[Error] Internal: Uncaught exception thrown of type RuntimeException.
Please file a bug report at https://github.com/kframework/k/issues
```

**Comment by dwightguth** [comment]
As I said to Radu via IM, we can't really help this because stratego is being not nice to us. So we are going to just suppress the check on this piece of code.

**Comment by radumereuta** [comment]
It's starting to work now. @dwightguth please review.

**Pull request merged**
