### PR TITLE
Cell fragment

### PR DESCRIPTION
**Pull request by daejunpark**
do not review.

### CODE REVIEW

**Comment by daejunpark** [comment]
@bmmoore please review. Note that I implemented this by using your existing implementation as a black box, since as Grigore said, cell-fragment will be eventually re-implemented. Regarding cell parsing, I reported an issue #1842, which will be handled at a separate PR. Until then, I used a simple workaround of declaring additional production.

**Comment by cos** [comment]
@bmmoore, as you ok with the change? Is it ok for @daejunpark to merge?

**Comment by bmmoore** [comment]
I really dislike how this works by adding and removing dummy cells (and treating k specially in the process). I'm trying to work out if this pass can be done more cleanly.

**Comment by cos** [comment]
@bmmoore, have you figured out a cleaner solution in the meantime by any chance? Otherwise, can we merge this for now and add an issue to track that this needs improvement?

**Comment by bmmoore** [comment]
Please see #1890 for my revisions.

**Comment by daejunpark** [comment]
@bmmoore @cos please review. We already reached the agreement to merge it for now, so please merge this long-standing (for a month!) PR asap. @cos, I had merge conflicts due to your transformer update. Please take a look if I made a right change: fca4f30

**Comment by cos** [comment]
fca4f30 looks good to me. I agree we should merge.

**Comment by bmmoore** [comment]
Merging this solution as agreed. Hopefully this can be simplified as in #1890, once I get that working.

**Pull request merged**
