### PR TITLE
make KApply be a KCollection

### PR DESCRIPTION
**Pull request by cos**
small but important change

### CODE REVIEW

**Comment by cos** [comment]
@dwightguth, @bmmoore small one, please have a look.

**Comment by dwightguth** [comment]
Is this really needed? You can always just access the KList directly... If you really think this is important though, I don't necessarily have a complaint, but you need to make the methods that you added to KItemRepresentation work correctly. It shouldn't be hard.

**Comment by cos** [comment]
> Is this really needed?

Unfortunately `KSeq` and `KRewrite` are not `KApply`s -- I would preferred them to be but it was beyond me. I want to be able to not care about what I'm traversing and `KCollection` gives me that.

> If you really think this is important though, I don't necessarily have a complaint, but you need to make the methods that you added to KItemRepresentation work correctly. It shouldn't be hard.

The backend is smaller than before but still has quite a few classes, so it's not trivial. I prefer to wait for Andrei to do it. I'll add an issue for this and bug him.

**Comment by bmmoore** [comment]
I don't really see the point of this, but at the very least you need to document the KCollection class if you do.

**Comment by cos** [comment]
Jenkings, test this please

**Comment by cos** [comment]
@andreistefanescu has already picked up the backend implementation of the missing methods. If nobody complains, I would merge this now so I don't get stuck with a subsequent pull request.

**Comment by cos** [comment]
Jenkins, test this please

**Comment by dwightguth** [comment]
lgtm

**Pull request merged**
