### PR TITLE
evict stuff from kparser cache

### PR DESCRIPTION
**Pull request by dwightguth**
@radumereuta please review

### CODE REVIEW

**Comment by radumereuta** [comment]
merge if tests pass, but I think someone else who understands how nailgun works should also have a look at this kind of diffs.

**Comment by dwightguth** [comment]
Haha this has more to do with classloaders than anything else. @bmmoore do you have any perspective? You are probably the most knowledgeable about java.

**Comment by dwightguth** [comment]
@radumereuta I added a fix to allow exceptions thrown by JSGLR to bubble up to the catch block you created in your pull request earlier. Please re-review.

**Comment by radumereuta** [comment]
lgtm

**Pull request merged**
