### PR TITLE
refactorings and fixes throughout

### PR DESCRIPTION
**Pull request by cos**
- the `moduleQualifySortPredicates` pass is not reused so memoization doesn't create problems anymore; when reusing a pass, memoization will remember results from previous runs --  will eventually have to make sure this problem cannot appear in other cases.
- `GenerateSortPredicateSyntax` is applied to `localSorts` only so it doesn't generate redundant subsorts anymore, and `BOOL-SYNTAX` is only imported when not there
- removed a redundant recursion in `RuleGrammarGenerator` - @radumereuta, have a look if you can
- `localSorts` and `listProductions` in `Module` are trimmed down of inherited stuff

### CODE REVIEW

**Comment by cos** [comment]
anyone, please review

**Review by daejunpark — APPROVED** [review]

**Comment by daejunpark** [comment]
@cos could you explain why the second bullet matters? is there any problem due to that?

**Comment by cos** [comment]
before it was spamming the modules with sort predicates that were already defined in imported modules. now each module only defines sort predicates for the sorts the are introduced by it.

for imports, it only imports the `BOOL-SYNTAX` module when it hasn't already been imported via some other import path.

**Comment by daejunpark** [comment]
ok, you can merge if you want

**Comment by cos** [comment]
I need a review through github to merge. Also, it would be great if you could merge once it passes CodeShip again -- there seems to be a problem with a Java core dump, bit strange.

**Comment by daejunpark** [comment]
for the codeship fail problem, i just sent an email. we can discuss over it.

**Pull request merged**
