### PR TITLE
Symbolic module

### PR DESCRIPTION
**Pull request by andreiarusoaie**
Added back the (basic) symbolic backend as a separate module.
@dlucanu @dwightguth please review

### CODE REVIEW

**Comment by andreiarusoaie** [comment]
This is not working. Seems that the tool changed significantly in the last few days.

**Comment by dlucanu** [comment]
This is contrary to the modular approach. If a feature is developed as a separate module, then its functioning shouldn't be affected by the the change of the main tool. 
Did these last changes affected the modular approach?

In this way we cannot progress too much.

**Comment by andreiarusoaie** [comment]
It seems that a method disappeared and some other methods have changed their arguments (they are related to the context object). I have revisited my code and fixed the easy errors, but I still have to fix some error related with the  Maude generation - don't know yet what the problem is. As soon as I finish,  I will create a new pull request.

**Comment by grosu** [comment]
Dorel, that will only happen once KORE will be fully incorporated in the tool; until then, things might still have to change.  For example, as you know, we are in process of eliminating the Context object.  If as part of the module you used some method that gave you the Context object, then there is obviously a problem, which I currently don't know how to solve except for gradual changes in the modules, as well.

Or Cosmin, do you think that your translator KORE2KIL will take care of that, so modules implemented using the old data-structures can just use your converter?

Grigore

**Comment by dlucanu** [comment]
Grigore, thank you for explanations. You are right, these changes can be done only gradually. For us is a bit difficult to keep the trace of all changes and to realise which ones affect our work. But we try to figure it out in order to make progress.

**Comment by osa1** [comment]
> It seems that a method disappeared and some other methods have changed their arguments (they are related to the context object).

@andreiarusoaie, if you need some state/methods in Context, comment at #1110 or at mailing list discussion. I'm hoping to merge Context changes gradually and unless you merge Symbolic backend first, you may have compilation problems with every change.

**Comment by grosu** [comment]
No, the idea is to keep the backends as separate modules, except for the main Java backend.  So some method needs to be found by which the existing backends are modified incrementally, until we finally reach the KORE fixedpoint of the internal representation.  (A message about that will be sent soon.)  One of the reasons for which we separated the backends as modules is exactly because we do not want to maintain all of them each time we do a refactoring.  So, for now, the best we can do is that you guys stay closely in the same loop until the transition happens, hopefully very soon.

Grigore

**Comment by dwightguth** [comment]
I should clarify also that the intent of the modularization is to keep the core of the K framework easy to maintain by putting the onus of ensuring that the module compiles and works correctly on the module developer rather than on the K team. As such, I suggest you work with us to create a separate repository in the kframework organization containing this code which contains the complete information of how to install the module and what version of the K framework it works with.

**Pull request closed without merging**
