### PR TITLE
Kastparser

### PR DESCRIPTION
**Pull request by liyili2**
first version

### CODE REVIEW

**Comment by grosu** [comment]
What?  332 files changed for the kast parser?  This makes no sense!

Grigore

**Comment by liyili2** [comment]
I merge several times with the new unified-builtins2 branch.

If you want, I can download the new branch, put all the changes manually and submit it again.

**Comment by radumereuta** [comment]
This should commit into unified builtins, not into master. Liyi, please change it from the top of the page.
If you will come to Siebel today, I can show you how.

**Comment by dwightguth** [comment]
@grosu this pull request contains a bunch of commits it shouldn't, that's why.

@liyili2 I can't review this until the diff is cleaned up. Get either Radu or me to show you what to do.

**Pull request closed without merging**
