### PR TITLE
Verification with floating point 2

### PR DESCRIPTION
**Pull request by yilongli**
Proved the complete cd2d program
@andreistefanescu @dwightguth please review

### CODE REVIEW

**Comment by andreistefanescu** [comment]
lgtm.

**Comment by dwightguth** [comment]
Merge if tests pass

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
It's not clear to me why this build timed out. I'm going to have to investigate it some more.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by yilongli** [comment]
Dwight, don't waste time on this one. It's because the prover is so fragile that even including one more function definition involving floating point will somehow break the merge sort example.

**Pull request merged**
