### PR TITLE
refactoring / delete old definition files

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by cos** [comment]
@andreistefanescu, did I carve out too much or too little?

**Review by andreistefanescu — APPROVED** [review]
More cleanup, this looks good!

**Comment by daejunpark** [comment]
@andreistefanescu `verification_lemmas.k` is not used any more?

**Comment by andreistefanescu** [comment]
It is not used by kernelc verification. It may be used by the large
languages though...

**Comment by cos** [comment]
Added a tag in case anyone needs something from there in the future:
https://github.com/kframework/k/releases/tag/before-deleting-old-builtins

**Pull request merged**
