### PR TITLE
update kdoc skeleton for new pipeline

### PR DESCRIPTION
**Pull request by dwightguth**
**do not review**

### CODE REVIEW

**Comment by cos** [comment]
@dwightguth, this is quite large so we should probably merge it separately. Could you add a bit of documentation for the new code, and I can review it quickly?

**Comment by cos** [comment]
@dwightguth, this is on the critical path to kdoc. Can you pick this up soon, or should I go ahead and add some documentation?

**Comment by dwightguth** [comment]
I fixed the conflicts and added Javadoc for the new classes. Did you want something else in the way of documentation as well?

**Comment by cos** [comment]
Doesn't compile anymore. It's in your fork so I cannot fix it myself.

**Pull request merged**
