### PR TITLE
Fix #683

### LINKED ISSUE #683: ktest generates no pdf, but a log file, and reports SUCCESS
What happens below makes no sense:

```
fslwork$ pwd
/home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_1
fslwork$ ls
imp.k  media.properties  NOTES  README.md  tests
fslwork$ ktest tests/config.xml 
Running initial scripts...
SUCCESS
Kompile the language definitions...(1 in total)
SUCCESS
Generate PDF files...(1 in total)
SUCCESS
Running /home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_1/imp.k programs... (8 in total, 0 with input, 8 with output, 0 with error)
SUCCESS

SUCCESS
----------------------------
Definitions kompiled: 1 (time: 0'9'' elapsed, 0'9'' CPU)
PDF posters kompiled: 1 (time: 0'8'' elapsed, 0'8'' CPU)
Programs krun: 8 (time: 0'3'' elapsed, 0'23'' CPU)
Total time: 0'20'' elapsed, 0'40'' CPU
----------------------------

fslwork$ ls
imp.k  imp-kompiled  imp.log  media.properties  NOTES  README.md  tests
fslwork$ 
```

1) ktest should NOT report success if it cannot generate the PDF correctly.

2) ktest should generate no imp.log file.

How can we even have this bug unnoticed for so long?  Aren't anybody else using ktest?

### PR DESCRIPTION
**Pull request by osa1**
#683

Note that I didn't change the error message. @grosu if you tell me what message to print I can update.

### CODE REVIEW

**Comment by grosu** [comment]
I cannot test it now, but I would not be that worried about the precise error message right now, as far as it is an error.  We can work on the message later, as we run into the error.

**Comment by osa1** [comment]
This looks bad. Build is failed because pdflatex returning non-zero for some cases. Can someone with pdflatex experience help us here?

**Comment by dwightguth** [comment]
Looks like the jenkins server was missing one of the needed packages we mention in the install file. I installed it, so we'll see what happens when I run Jenkins again.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Looks like something broke CIL. Jenkins wasn't configured right, I'm going to rerun this so I can see the error message.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Okay so the issue here is that this pull request was made against master and so it used the master version of the floats, but CIL is set up to work with unified builtins. I think the correct thing to do in this case is just to merge despite the failure. When you make a pull request merging this change into unified-builtins (and that is now your responsibility to do) you will find out for sure if you broke CIL, although I can't see how this change could have.

**Pull request merged**
