### PR TITLE
allow . for .K

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by daejunpark** [comment]
@cos It seems that all we need to complete this PR is just to adjust tests, right? I can take it over, if you want.

**Comment by cos** [comment]
thanks @daejunpark, it's ok. already have the rest of the fixes... let's see if it passes now.

**Comment by cos** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
lgtm.

**Comment by grosu** [comment]
thanks, @cos.  lgtm, too.  @daejunpark , let me know when I can revise kool-untyped again.

**Pull request merged**
