### PR TITLE
removed duplicate rules in indexing table

### PR DESCRIPTION
**Pull request by yilongli**
@dwightguth please review

### CODE REVIEW

**Comment by yilongli** [comment]
Since `ImmutableSet` also has fixed iteration order, it 's ok to replace `List` with it.

**Comment by dwightguth** [comment]
I'd feel better if  you made the variables expect an ImmutableSet instead of a Set, if you are relying on the details of a particular Set implementation.

**Comment by yilongli** [comment]
Well, if the rewrite engine is bug-free, then it doesn't matter if the rules are stored in an ImmutableSet or HashSet. I am only using ImmutableSet for easy debugging.

**Comment by dwightguth** [comment]
Well we actually want a deterministic ordering of rule applications, don't
we? it protects us against issues arising from non confluent definitions as
the framework evolves.

**Comment by yilongli** [comment]
I am not sure that we always want deterministic ordering of rule applications. In the case of non-confluent definitions, shouldn't we expose and fix them as early as possible?

**Comment by dwightguth** [comment]
Well, yes, I agree that we should be able to expose non confluent
definitions. However, I think it will be more effective to do this by means
of a flag to kompile that randomizes the execution order of the rules than
to try to cling to the notion of nondeterministic set iteration, when it's
always the same for any given JVM version.

**Comment by yilongli** [comment]
Sure.

**Comment by yilongli** [comment]
Done. @dwightguth

**Pull request merged**
