### PR TITLE
Fix strict hole sort

### PR DESCRIPTION
**Pull request by daejunpark**

### CODE REVIEW

**Comment by daejunpark** [comment]
todo: fix sort lattice issue

**Comment by daejunpark** [comment]
this will fix the recurring issue #1692

**Comment by daejunpark** [comment]
@andreistefanescu please review

**Comment by dwightguth** [comment]
Hold on a sec. This is a change being made to the core compilation pipeline in order to solve an issue in the Java backend. That seems strange to me, and in particular I don't know how this change will affect the C semantics. Can you justify the change to the core of the K language by explaining how the passes worked before and after, and why you think they behaved incorrectly before?

**Comment by andreistefanescu** [comment]
This change preserves the sort information for heating/cooling rules, thus making the sort information consistent across all rules. You are free to discard it in the ocaml backend.

**Comment by dwightguth** [comment]
Okay, that sounds like a good change, but I was looking for more
information. More concretely, what is the change made to the semantics of
strict and contexts? Like, what rules were generated before and after the
change? How was consistency violated in the old semantics?

**Comment by andreistefanescu** [comment]
Let's say you would manually write a heating rule:
`HOLE + K => HOLE ~> freezerPlus(K)    requires notBool isKResult(HOLE)    [heat]`
Then the sort inferencer would infer the sorts `Exp` for `K` and `HOLE`, which the java backend would use, and the ocaml backend would discard. Before the change, the heating rules were generated without this inferred sort information. This leads to a bunch of small issues, that both me and @daejunpark hit. This change should add the inferred sort information to the rule.

**Comment by dwightguth** [comment]
Oh, okay, I see. In that case, can you please disable this change if the
user passes the --non-strict flag?

**Comment by daejunpark** [comment]
The sort preservation is disabled, thus this change has no effect, when `--non-strict` option is given.

**Comment by dwightguth** [comment]
lgtm

**Pull request merged**
