### PR TITLE
Freezing the code for path indexing

### PR DESCRIPTION
**Pull request by owolabileg**
The path indexing now works for most languages in the K tutorial. Stopping work on it for now, so that I can move to  a more general algorithm.

### CODE REVIEW

**Comment by dwightguth** [comment]
hmm not really sure why this code isn't testing itself...

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
add to whitelist

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by owolabileg** [comment]
I think this was because I forgot about the copyright information. I've added them now. Sorry about that.

**Comment by dwightguth** [comment]
Jenkins: test this please.

**Comment by dwightguth** [comment]
Can you please add @Deprecated attributes and @deprecated javadocs to the top-level entry points of this code path? The understanding I reached with Andrei was that this would be an unsupported change which we commit because when it works, it's a speedup. But that if we needed to make changes in order to make it work we would just revert back to the old algorithm. Hence I believe @deprecated is appropriate.

Once you do this, I will merge.

**Comment by owolabileg** [comment]
Okay, I made the changes requested by @dwightguth. Do they suffice?

**Comment by dwightguth** [comment]
Typically both the @Deprecated attribute and the @deprecated javadoc are applied to every instance of a deprecated object. Also, can you deprecate the enum constant in KompileOptions?

**Comment by owolabileg** [comment]
Done.

**Comment by dwightguth** [comment]
Looks good, but as I said, can you please deprecate IndexingAlgorithm.PATH?

**Comment by owolabileg** [comment]
I already marked that constant as Deprecated. Maybe I am missing something else?

**Comment by dwightguth** [comment]
I'm sorry, I missed it. Merging.

**Pull request merged**
