### PR TITLE
initial commit for Google Guice

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**
- Use dependency injection to bootstrap the tools
- Add static injections for code that will no yet be initialized by Guice, and deprecate global static state
- reorganize the way the tool boots by creating a common FrontEnd class.

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@cos please review. Anyone who knows anything about dependency injection, please review also. Others can review too since this is a cross cutting change.

I suggest strongly that anyone who reviews this find me and talk to me unless they are already familiar with dependency injection or Google Guice.

**Comment by cos** [comment]
It looks good overall. One minor concern are the @First, @Second annotations which could have more meaningful names.
I have a long flight today and will give it a closer look offline.

**Comment by cos** [comment]
aside from the @First, @Second, it looks good overall. from my perspective, it is good to merge.

**Pull request merged**
