### PR TITLE
add ktest for ocaml backend

### LINKED ISSUE #1685: KTest for OCaml backend
@dwightguth, if you are going to insist that we not merge commits that break the OCaml backend, you should get jenkins to test it.

### PR DESCRIPTION
**Pull request by dwightguth**
@bmmoore please review

fixes #1685

### CODE REVIEW

**Comment by bmmoore** [comment]
Looks like a reasonable example

**Comment by bmmoore** [comment]
Looks like you need to install ocaml on the jenkins box

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
