### PR TITLE
Dnf fix

### PR DESCRIPTION
**Pull request by andreistefanescu**

### CODE REVIEW

**Review by bmmoore — CHANGES_REQUESTED** [review]
The DNF change should correct the results, but this pull request shouldn't include the caching commit de939992b7f8fd02698d41509a2c9abafa0e9618

The K repository now prefers to rebase pull requests onto master. I think de9399 is the non-rebased version of a change that was already applied.

**Comment by andreistefanescu** [comment]
@bmmoore ups, you are right

**Comment by grosu** [comment]
Guys, can you please merge this?  I'd like to release the ERC20 spec tomorrow.  Thanks.

**Review by cos — APPROVED** [review]
looks good

**Review by bmmoore — APPROVED** [review]

**Comment by daejunpark** [comment]
lgtm.

**Pull request merged**
