### PR TITLE
Keep location information of KItem in Java backend

### PR DESCRIPTION
**Pull request by daejunpark**
for the Jenkins test

### CODE REVIEW

**Comment by dwightguth** [comment]
Can you explain what in particular you want to use this information for?

**Comment by andreistefanescu** [comment]
lgtm

**Comment by daejunpark** [comment]
I need this information for measuring semantics test coverage in the term-level granularity.

Suppose that we have the following K definition:

```
...
PseudoCode ::= "If" K "then" K "else" K
...
rule a1(x) => If x then b(x) else c1(x)
rule a2(x) => If x then b(x) else c2(x)
...
```

Currently, what we can measure is whether the rule `a1(x)` is applied or not, but we cannot measure which branch (i.e., `b(x)` or `c1(x)`) is taken. Also, if we have the same terms in multiple places (i.e., `b(x)`), we need to distinguish it based on where it came from.

So, my solution for the problem is to maintain location information for term-level, which allows to measure location information of all terms that have been in the top of the K cell. For now, I think `KItem` is sufficient for my purpose.

**Comment by daejunpark** [comment]
@yilongli could you please review this?

**Comment by grosu** [comment]
This is needed to evaluate the semantic coverage of a test suite, i.e, how well a set of programs covers the semantics.  Daejun crafted this by hand for his JavaScript semantics, and he found several behaviors which were undefined by the Ecmascript test-suite.  Interestingly, those turned out to be mis-implemented by browsers, so he found bugs in Chrome, IE, Firefox, Safari.  So we really want this feature in the K framework.

Grigore

**Comment by yilongli** [comment]
Lgtm

**Pull request merged**
