### PR TITLE
fix java-semantics performance problem

### PR DESCRIPTION
**Pull request by yilongli**
@dwightguth @laurayuwen please review

### CODE REVIEW

**Comment by dwightguth** [comment]
Looks like there is another issue with the ordering of search solutions here. I think we should probably try to lexicographically sort the results in order to avoid this issue. But feel free to defer that to a later pull request if you want.

**Comment by dwightguth** [comment]
lgtm otherwise

**Comment by laurayuwen** [comment]
lgtm. The speed is normal now.

**Comment by dwightguth** [comment]
@yilongli feel free to un-revert the change involving parallel streams also if you want.

**Comment by yilongli** [comment]
@dwightguth I don't understand why the ordering of the search solutions is not sorted. In [PrintSearchResult](https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/backend/unparser/PrintSearchResult.java), the solutions are put into a `TreeSet`. Any idea?

**Comment by dwightguth** [comment]
I believe that that test is running on the KORE pipeline where the same thing has not been done yet. Take a look at KRun.printSearchResult.

**Comment by yilongli** [comment]
OK, it's a bit difficult to sort the search results in the KORE pipeline so I just revise the code to be more deterministic.

**Pull request merged**
