### PR TITLE
further improve code related to PatternMatcher

### PR DESCRIPTION
**Pull request by yilongli**
Nothing really interesting, mostly refactoring.

### CODE REVIEW

**Comment by yilongli** [comment]
@andreistefanescu @dwightguth please review

**Comment by dwightguth** [comment]
lgtm. @andreistefanescu merge if you are happy

**Comment by andreistefanescu** [comment]
Looks good. There a lot of code movement thought, so I might have missed something... My only question is whether the recursive pattern matcher is still used anywhere.

**Comment by yilongli** [comment]
Yes, it's still used in searching because the non-recursive one cannot handle AC matching yet.

**Pull request merged**
