### PR TITLE
fix some bugs in ListBuiltin

### PR DESCRIPTION
**Pull request by dwightguth**
- make CollectionBuiltin abstract
- make ListBuiltin constructors take List
- make ListBuiltin constructor private
- fix bugs in ListBuiltin.of
- Make #noIO not require a list variable

### CODE REVIEW

**Comment by dwightguth** [comment]
@andreistefanescu please review.

**Comment by andreistefanescu** [comment]
Do you need to make any modifications to the transformers?

**Comment by dwightguth** [comment]
If I understand correctly, the one line change to AbstractVisitor which causes it to call ListBuiltin.of when it copies objects should be sufficient to take advantage of this diff.

**Comment by andreistefanescu** [comment]
lgtm

**Pull request merged**
