### PR TITLE
Fix2212

### PR DESCRIPTION
**Pull request by xc93**
Add regression test for bug #2212.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/148313234996210/224288625194930)

### CODE REVIEW

**Comment by cos** [comment]
I don't see the connection between the code and #2122.

**Review by cos — CHANGES_REQUESTED** [review]
I don't see the connection between the code and #2122.

**Comment by xc93** [comment]
@cos Sorry, it's #2212 . I made a typo.

**Comment by daejunpark** [comment]
Close this PR exercise in the class.

**Pull request closed without merging**
