### PR TITLE
Splitted Flatten Syntax in two.

### PR DESCRIPTION
**Pull request by traiansf**
This is the same change as #302, only this time applied on the master branch.  If this passes tests, you can merge it and I'll merge master into unified-builtins then (so we can remove the other pull request).

### CODE REVIEW

**Comment by traiansf** [comment]
Ok. good we did not commit it on the branch. There were some issues in krun, which run FlattenSyntax, but on terms not on definitions.
Now it's ready for review & approval

To answer the questions there, indeed FlattenSyntax&FlattenTerms are obtained by splitting the original FlatenSyntax in two, and added a call to FlattenTerms in the transformer for Definition of FlattenSyntax to avoid updating the list of Transformation for the 7-8 backends.

**Comment by dwightguth** [comment]
If you fix the KilProperty thing that I talked about, and get @radumereuta or @liyili2 to sign off on this, you can merge it.

**Comment by radumereuta** [comment]
That was surprisingly easy to fix.
lgtm

**Comment by traiansf** [comment]
@dwightguth: I've modified the KilProperties, added Javadoc for them, added both to the FlattenSyntax for now (took a couple of minutes and google searches to figure how that is done) and all tests passed.  As @radumereuta gave his ok, I'm merging this.

**Pull request merged**
