### PR TITLE
removed NonACPatternMatcher from use

### PR DESCRIPTION
**Pull request by andreistefanescu**
do not review

### CODE REVIEW

**Comment by andreistefanescu** [comment]
@dwightguth please review

**Comment by dwightguth** [comment]
Can you run the code before and after this diff on one of the larger examples in the tutorial and tell me the effect on the performance of the pattern matching rewrite engine?

**Comment by andreistefanescu** [comment]
This slightly improves performance: collaz (n=500) went from 1.45m to 1.25m.

**Comment by grosu** [comment]
Which language are you talking about?  IMP, SIMPLE, KOOL, C, Java?  Please say one of the latter :)  The performance seems low though, even for C.  How many rewrites were applied?  nailgun?  Thanks, Grigore.

**Comment by andreistefanescu** [comment]
This numbers are for kool-typed-dynamic. It takes 1,692,296 steps.

**Comment by grosu** [comment]
So about 20,000 steps/s, right?  How about running it with Nailgun enabled?

**Comment by andreistefanescu** [comment]
About 23,000 steps/s. I did not get a chance to run it with nailgun yet, but I don't think it would improve by very much.

**Pull request merged**
