### PR TITLE
Fixing issue #475. I've made a change a while back to fix latex,

### PR DESCRIPTION
**Pull request by radumereuta**
but that broke warning reporting for typed variables.

Also, unfortunately I can't add a regression test, because ktest doesn't allow me to compare the output of kompile.

### CODE REVIEW

**Comment by dwightguth** [comment]
Make a unit test then. Something minimal that is expected to throw a
KEMException.

**Comment by dwightguth** [comment]
No sorry I guess it would assert something about a KException, since it's a
warning and not an error.

**Comment by radumereuta** [comment]
I'm not sure how to do that.

**Comment by radumereuta** [comment]
Also. A test would not fit in the JUnit philosophy of being fast.
I have to run the entire kompile in order to properly test this (well... the expensive part at least).

**Comment by dwightguth** [comment]
I don't understand. If the warning is generated by VariableTypeInferenceFilter when you have a certain type of rule, just construct such a rule as input, then call VariableTypeInferenceFilter on it. You can mock any dependencies necessary. What's the complexity here?

**Comment by radumereuta** [comment]
@dwightguth  please review. I think it's ready for merge.

**Pull request merged**
