### PR TITLE
Make things working with Java 8

### PR DESCRIPTION
**Pull request by osa1**

### CODE REVIEW

**Comment by osa1** [comment]
@andreistefanescu can you have a quick look at https://github.com/osa1/k/commit/fdd6cf9a7b54e7a2aba4c18cac7fc341c131c9bf and tell us if that change is OK? I'm not fixing subsorting stuff because no one really knows how are they supposed to work and this change doesn't make it more wrong that it was before. (no algorithms are changed, I just adapted the output file for fixed iteration order of some unordered containers like set, map etc. see https://github.com/osa1/k/commit/ef018965ffe8a3c3677bb3e7f3d418123535a0b9)

**Comment by dwightguth** [comment]
lgtm. Once you satisfy Andrei, I will update jenkins to use Java 8, and then rerun the test suite, merging it when it passes.

**Comment by osa1** [comment]
I think this patch is ready for merge.

**Comment by andreistefanescu** [comment]
lgtm

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
You need to talk to @andreistefanescu about some of the stuff you just did with the kem, because some of those things he may wish to be nonfatal errors, and output only a warning.

**Comment by osa1** [comment]
@yilongli I had to remove the problematic test case instead of commenting it out, because of limitations of XML comment syntax. I'll put a note in #1046 about this and we can make sure that the test will be put back when it comes to closing #1046 . Does that sound good?

**Comment by yilongli** [comment]
I just told you that you could do something like this: https://github.com/kframework/k/blob/master/k-distribution/samples/java_rewrite_engine/tutorial/2_languages/1_simple/1_untyped/tests/config_verification.xml

**Comment by osa1** [comment]
Done.

**Comment by yilongli** [comment]
I am fine with this but @andreistefanescu shoud take a look. I will try to fix the merge_sort example asap.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
