### PR TITLE
Small bug fix for graph in rewriter.

### PR DESCRIPTION
**Pull request by msaxena2**
Small fix to set final state in case of finite steps in symbolic rewriter.

### CODE REVIEW

**Comment by msaxena2** [comment]
@dwightguth please review

**Comment by traiansf** [comment]
@msaxena2 @dwightguth I have some questions about these pull requests: Can I get the graph of all possible transitions in one step with the code that you're adding?

I need that for my work on the model checker, but I guess it would be useful for a debugger, too, so I was wondering if you implemented that or you plan on implementing that anytime soon.

**Comment by dwightguth** [comment]
When it's ready, you should be able to get a graph from any KRun execution. The code is currently untested though and likely contains bugs.

**Comment by dlucanu** [comment]
This is a good news. I know that it is not easy to estimate about the time it is done, but a clue will be very helpful.

**Comment by traiansf** [comment]
@dwightguth Just to make sure: execution includes search?  And we would not mind being alpha-testers

**Comment by dwightguth** [comment]
search is currently unimplemented. Patches are welcome, or Manasvi will likely get to it when he reaches that point.

**Pull request merged**
