### PR TITLE
Rename KVariable to #KVariable to allow bidings (see #1402).

### PR DESCRIPTION
**Pull request by radumereuta**
@dwightguth please review.

### CODE REVIEW

**Comment by dwightguth** [comment]
You should also remove the KVariable case from RuleGrammarGenerator now that it begins with a hash.

**Comment by grosu** [comment]
Would this be a good moment to also rename Variable to KVariable in what the user sees in K definitions, to be consistent with KResult, KItem, etc.?

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@radumereuta it looks like you need to push a new commit to github to make Jenkins pick up your build.

**Comment by radumereuta** [comment]
@dwightguth please re-review. Tests passed.

**Pull request merged**
