### PR TITLE
fix for #1705

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by radumereuta** [comment]
@bmmoore please review.
I've been working with @cos to fix issue #1705.
This replaces an older try of mine which wasn't really clean.
Basically we've extended the implementation of Module to automatically add the subsort production between two lists which have related elements. This is done automatically, and is consistent with what @grosu was saying in #1733.

The only problem with doing this automatically is that we don't want that production to be included in the parser for programs, and I solve this by a simple check when I'm generating the grammar for programs.

This should also solve some recent issues with Simple.

**Comment by bmmoore** [comment]
The line I commented on looks like a mistake, please explain it. I didn't see a compensating change elsewhere, so I don't know how both versions can even pass tests, unless that attribute is unused or we have insufficient tests.

Have you updated any definitions to depend on the extra subsorting? It seems like this shouldn't affect parsing at all, is it useful for anything yet?

My commit should be a simple merge to catch up with changes in master, but please check over it. There was a merge conflict in `outer.scala`.

**Comment by cos** [comment]
@bmmoore, yes, that bug slipped in, thanks!

@radumereuta, if you know where such sub-sorting appears in the tutorial, could you have a go at it? Otherwise, I can make the changes.

**Comment by radumereuta** [comment]
The test that I added doesn't work without the inferred subsort.
In the tutorial, this is needed at least for Simple. (see #1827 @daejunpark comment from Nov 10).

**Comment by bmmoore** [comment]
The fix looks fine.

**Comment by cos** [comment]
correct

**Comment by radumereuta** [comment]
So, ok to be merged now?

**Comment by bmmoore** [comment]
Add a test that would have caught that bug. I'm still surprised `mvn verify` passed, I thought it would parse all the nils as the wrong label!

**Comment by radumereuta** [comment]
Which bug? The subsort to KResult? That should have been taken care by the `kool` programs.
But what baffles me right now, is that the test failed, then I merged master and they passed, although they shouldn't, then I've re-added the subsort, and passed again.

**Comment by bmmoore** [comment]
I mean the one fixed in 8a85bec, where you had been giving the nil production the same klabel as the cons productions.

**Comment by radumereuta** [comment]
Does this test look good?

**Comment by bmmoore** [comment]
That looks good, as long as actually it fails if you (temporarily) undo 8a85bec. I'll try running it.

**Comment by bmmoore** [comment]
That test doesn't work, it's the `Es#Terminator ::= "" [klabel('.Es)]` production which was affected.

**Comment by radumereuta** [comment]
Yes, you are right, I forgot to test for programs also.

**Comment by bmmoore** [comment]
That test also doesn't find any problems. You should be able to run a command like this and get the last message:

```
$ mvn package && git revert --no-edit 8a85bec && ! mvn package && echo "Test is strong enough"
```

Actually, the apply function in `definition.Production` adds an additional klabel attribute based on the first argument, so some code might work after reverting 8a85bec depending on which klabel attribute the set returns. But, your test still "passes" even if after reverting that commit I also edit RuleGrammarGenerator.java#274 to construct the production as

```
prod1 = Production(ul.klabel, Sort(ul.sort + "#Terminator"), Seq(Terminal("")),
        newAtts.add(Constants.ORIGINAL_PRD, ul.pTerminator))
```

We need a regression test that would actually test that these productions are actually used correctly in the parser, or perhaps to explain why the klabel assigned there is never actually used.

**Comment by radumereuta** [comment]
Right again.
I made sure this time that all the productions generated for program lists are verified in the test, for both `*` and `+`.

**Comment by cos** [comment]
@radumereuta, this is more your PR than mine. 

If you consider the issue fixed, please mark it as `ready-for-review` so @bmmoore can merge it.

**Comment by bmmoore** [comment]
Okay, these tests still don't actually catch the bug fixed in 8a85bec, but everything else seems to work (and we've fixed that bug), so I'm going to merge this and open a new pull request for sorting out the regression tests.

**Comment by bmmoore** [comment]
I made pull request #1917, which starts by reverting 8a85bec, to continue figuring out why those tests don't work.

**Pull request merged**
