### PR TITLE
remove unsupported map builtin function

### PR DESCRIPTION
**Pull request by daejunpark**

### CODE REVIEW

**Comment by daejunpark** [comment]
@kheradmand please review and approve this pull request.

**Comment by dwightguth** [comment]
FYI the C semantics uses this heavily for performance reasons.

**Comment by kheradmand** [comment]
@daejunpark 
maybe it would be a good idea just to comment it instead of removing. 

@dwightguth 
the feature is not implemented anyway (I guess), please look at #2273 and the problems it caused for me.

**Comment by daejunpark** [comment]
@dwightguth thanks for your comment. @kheradmand Now I keep `in_keys` in domains.k, but make java backend to throw exception when it is used.

**Comment by daejunpark** [comment]
@kheradmand could you approve this? You can click the link above and check a radio box to approve it.

**Review by kheradmand — APPROVED** [review]
lgtm

**Pull request merged**
