### PR TITLE
Traiansf review2

### PR DESCRIPTION
**Pull request by traiansf**
Ok, I did not know how to do this better, so I first merged master into unified-builtins (rebasing was simply unacceptable: it required me to resolve conflicts which I already had during previous rebase operations).
Once I merged, I simply branched from the merged branch and things became much simples as shown by this pull request.
If there is a better way, please let us know --- the instructions on the wiki seem to cover only patches to master.

### CODE REVIEW

**Comment by dwightguth** [comment]
If you are working on a branch of the unified-builtins branch, what you did makes sense. You can also rebase the traiansf-review2 branch against the unified-builtins branch once it has been merged into master, if you already have a branch open and need to resync your changes.

Can you provide me a little bit more detail about the precise workflow you want me to cover in the wiki?

**Comment by dwightguth** [comment]
lgtm. Can someone else familiar with the unified builtins work that Traian is doing weigh in to make sure they understand this change?

**Comment by traiansf** [comment]
Well, I would like to have some guidelines for when to do a merge and when
to do a rebase.
Originally, I thought we should always rebase to make sure the revisions
tree does not branch too much.
But apparently if more than one person works on the same branch and some do
merge while others rebase things get messy.  And I guess this is what
happened with the unified-builtins2 branch.

now, my original attempted workflow was:
(1) git checkout -b traiansf-review
(2) made my commits
(3) realized I needed the change you pushed into master
(3) git rebase origin/master
- here is where it stopped working, as there were lots of conflict
  between older versions of a file I was sure I had resolved once and now
  needed to resolve again
  hence, I gave up on that and did
  (3') git merge master
  (4) I created the first pull request, which you rightfully dismissed

my second attempt was much simpler (but I took advantage I had ownership of
the unified-builtins2 branch
(1) git merge origin/master  && git push unified-builtins2  --- no conflicts
(2) git checkout -b traiansf-review2
(3) made my commits
(4) second pull request

Now, what I'd like to know is:
- what is the downside of the second attempt --- I know the upside is that
  I don't have to solve conflicts
- what workflow schema should we adopt for our organization

2014-02-27 21:49 GMT+02:00 dwightguth notifications@github.com:

**Comment by dwightguth** [comment]
1. Rebase changes from upstream repositories. So when I make changes and push them and you need to resolve conflicts, that is a rebase. Or when someone makes changes to the main repo and you need to sync your fork, that is a rebase.
2. Merge changes between branches of the same repository, or when pushing a branch back into the main repository.  Never rebase if the change you are rebasing has already been committed to the main repository and might have been pulled by someone else.

So I think you were fine not to rebase in this case, because you would have been deleting a commit on the traiansf-review branch which others might already have pulled.

If you don't want to worry about this though, I suggest you work from a fork instead of from branches.

**Comment by dwightguth** [comment]
Hey FYI I had the same problem you're describing this morning and was able to fix it with rebasing. Eventually I realized the problem was that I had branched my branch off of the wrong parent commit and there was stuff in the log that I didn't realize was there which was messing up the rebasing process. So I had to cherry-pick my change onto a new branch which had the features I was looking for. Let me know if you want me to write it up.

Also: I'm still waiting on someone familiar with what Traian is doing with the builtins to sign off that they understand this change.

**Comment by traiansf** [comment]
Yes, creating a new branch and cherry picking also worked for me.  Maybe we
should write this up for future reference.

best wishes,
Traian

2014-02-28 18:57 GMT+02:00 dwightguth notifications@github.com:

**Comment by radumereuta** [comment]
It might be that only Traian knows these, but from what I can see, it's ok to merge.

**Comment by dwightguth** [comment]
If Traian is the only one familiar then we need to nominate someone else to become familiar by following his code reviews. We should discuss this at the meeting on Monday. Regardless, I will merge this for now.

**Comment by dlucanu** [comment]
I am familiar with the problem domain and I know most of the implemented algorithms, so I could be the second reviewer. Partially this is already achieved because we (Traian and me) are often discussing on the code.

**Pull request merged**
