### PR TITLE
Fixing issue 2182 

### PR DESCRIPTION
**Pull request by radumereuta**
Where multiple list productions for the same type of cells would interfere and use too much memory.

### CODE REVIEW

**Comment by dwightguth** [comment]
This is not really a good solution if type="Set", "Map", or "List". It won't actually target that production effectively in that case.

**Comment by radumereuta** [comment]
I found this problem only on parsing cells that have multiplicity="*" where the there were some productions added during configuration concretzation (I think). They were only using `Bag` and I didn't want to remove those since most likely they are used later, I just removed them from the parser. They were already tagged with `avoid`, so they weren't intended for parsing anyway. What we failed to anticipate, was how much of a problem they can cause at parsing time.

I'm not sure if it's the best solution, but it seems the least upset right now.

**Comment by radumereuta** [comment]
Ah, and its ready for review. Since you already started, @dwightguth please review.

**Comment by dwightguth** [comment]
It looks fine other than the comment that I included. There's actually a bug in ConfigurationInfoFromModule that got fixed in the rv-k by adding a cellCollection attribute on all cell collection productions. You might consider doing the same and then using that attribute here, the way I did. Otherwise you're going to have to be doing increasingly desperate guesswork in order to try to decide whether something is a cell collection...

**Comment by radumereuta** [comment]
@dwightguth please have another look. Those are flaky tests. Tested twice, and on my computer, and the tests work as intended.

**Comment by dwightguth** [comment]
looks fine, I'm not going to comment on the flaky test issue. someone else can take over the review from here.

**Comment by radumereuta** [comment]
@daejunpark please review.

**Comment by radumereuta** [comment]
Can someone else review this? Maybe @cos.

**Comment by cos** [comment]
Why are cell cell collections were interfering with `Bag` parsing? Is there some extra subsorting somewhere between `CellBag` and `Bag`?

**Comment by radumereuta** [comment]
I haven't looked too deeply into that, but most likely yes, through some indirect subsorts.
I just noticed those productions weren't supposed to be in the parser, and just removed them.

**Comment by daejunpark** [comment]
@radumereuta sorry for the delay. It looks good to me mainly because the change is small and seems natural, though I did not fully understand what's going on.

Let me try to use this branch to check it solved my original problem in addition to the simplified version I reported.

**Comment by daejunpark** [comment]
It seems to work for my original problem as well. @cos you can merge if you have no more concern with this.

**Pull request merged**
