### PR TITLE
Fixing #1521.

### PR DESCRIPTION
**Pull request by radumereuta**
@dwightguth please review.

### CODE REVIEW

**Comment by dwightguth** [comment]
Can you add a test?

**Comment by dwightguth** [comment]
This looks okay, but I still feel like having a  custom pass for this isn't really what we want... This will eventually lead to unsoundness in the unparser because you are not representing the priorities as actual priorities but rather handling them ad-hoc. I'm not going to oppose merging this because it gets the job done, but I strongly encourage you to consider automatically generating the relevant "syntax priority" statements rather than relying on a custom pass.

**Comment by radumereuta** [comment]
I will keep this in mind for the future. I would like to have the POSet performance fixed at least before I do this.

**Comment by dwightguth** [comment]
okay. lgtm.

**Pull request merged**
