### PR TITLE
better KORE transformers

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by cos** [comment]
@bmmoore, I moved and refactored a bit your `VisitK`and `TransformK` classes -- just to make things uniform. Also added a `FoldK` class.

**Comment by bmmoore** [comment]
Looks good after the commits I added. Did you move the `KRewrite` interface intentionally?

It's a bit unfortunate that the monoid for fold has to be declared just by implementing methods rather than something more reusable, but I guess that's the best we can do.

**Comment by cos** [comment]
no, moving `KRewrite` was not intentional. Thanks for removing the namespace references!

**Comment by cos** [comment]
shall we merge?

**Pull request merged**
