### PR TITLE
Error messages

### PR DESCRIPTION
**Pull request by daejunpark**

### CODE REVIEW

**Comment by daejunpark** [comment]
This change was already reviewed and merged via #2065 #2061 #2060 and #2043, but not applied to master due to incorrect base setting of PRs.

**Comment by cos** [comment]
@daejunpark, to make sure thing merge smoothly you can follow a simple rule: merge master into the branch before considering merging the branch into master.

**Comment by cos** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
@cos please review

**Pull request merged**
