### PR TITLE
Performance Improvements

### PR DESCRIPTION
**Pull request by msaxena2**
Serialization of Kore Definition via FST(http://ruedigermoeller.github.io/fast-serialization/) to improve performance.

### CODE REVIEW

**Comment by msaxena2** [comment]
@cos Please Take a look.

**Comment by cos** [comment]
This is not passing.

**Comment by msaxena2** [comment]
Yeah, for some reason builds on codeship are failing and taking longer. I suspect the problem is with  codeship and their load balancing. I'll take a look at it.

**Comment by msaxena2** [comment]
I'm closing this PR for now, it looks like it needs more work.

**Pull request closed without merging**
