### PR TITLE
Add parenthesis as brackets for sort K. #1932

### PR DESCRIPTION
**Pull request by radumereuta**
Let's see what fails.

### CODE REVIEW

**Comment by radumereuta** [comment]
@grosu please review.
I've added the parenthesis you asked in #1932, and other places.
I had to patch kool-untyped to make it work, since the type inferencer is not smart enough to disambiguate between `KItem ::= (Id,EnvCell)` and brackets around a list of `Exps` or `Ids`. Personally, I find this error the expected behavior. It is just ambiguous if you take into consideration only types, like I do in the type inferencer. If you don't like the result, then we have to use extra information in the disambiguation algorithm.

I don't have good internet this week, so don't wait for me to merge it if you need these changes.

**Comment by grosu** [comment]
The patch is OK, you are basically only casting _ to _::EnvCell to avoid the ambiguity.  That is acceptable, especially considering that we do not have module qualification yet.  So I'm going to merge this.  Thanks, @radumereuta .

**Comment by laurayuwen** [comment]
Just to make sure, this PR makes sure that we can write write parenthesis instead of back-ticks in definitions; but it does not deal with unparsing, right? I merged this into the tutorial branch I am working on, it does not change the output like this

```
lambda y . ` ` lambda x . lambda y . ` x y ` ` y `
```

**Comment by radumereuta** [comment]
Just parsing, haven't looked over unparsing.

**Comment by daejunpark** [comment]
@radumereuta just to make sure, you're considering the followings as well, right?

https://github.com/kframework/k/blob/80ed28cd8d962e8e347ad3ee16da3a90b87fa46b/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L461

https://github.com/kframework/k/blob/80ed28cd8d962e8e347ad3ee16da3a90b87fa46b/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L493

https://github.com/kframework/k/blob/80ed28cd8d962e8e347ad3ee16da3a90b87fa46b/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L556

https://github.com/kframework/k/blob/80ed28cd8d962e8e347ad3ee16da3a90b87fa46b/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L572

**Comment by radumereuta** [comment]
I've only added `( )`. I didn't remove the backtick ones. That will be left for a later date. I don't want to spend time now to fix the updated definitions.

**Comment by grosu** [comment]
@radumereuta : there should be no bacticks in any definitions by Jan 18.  Otherwise we are not done.  Because it means that we need to modify the readmes, the movies, etc.  I hope those backticks can be eliminated simply because we add the parentheses as brackets to the various domains.

**Comment by radumereuta** [comment]
The backticks can be eliminated right now. It's just not my top priority.
I made this PR so the original parenthesis based brackets can be used alongside backticks.
If someone has the spare cycles, can go into `kast.k` and eliminate the line where backticks are defined, and modify every definition that fails... It's just a semi-mechanical transformation.

**Comment by daejunpark** [comment]
@radumereuta No, it is not that simple. I already did what you suggested, but it didn't work. Why don't you try to fix one of the followings? You'll find hidden issues.

https://github.com/kframework/k/blob/80ed28cd8d962e8e347ad3ee16da3a90b87fa46b/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L461

https://github.com/kframework/k/blob/80ed28cd8d962e8e347ad3ee16da3a90b87fa46b/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L493

https://github.com/kframework/k/blob/80ed28cd8d962e8e347ad3ee16da3a90b87fa46b/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L556

https://github.com/kframework/k/blob/80ed28cd8d962e8e347ad3ee16da3a90b87fa46b/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L572

**Pull request merged**
