### PR TITLE
More cleanup

### PR DESCRIPTION
**Pull request by yilongli**
do not review yet

### CODE REVIEW

**Comment by yilongli** [comment]
jenkins: test this please

**Comment by yilongli** [comment]
Jenkins: test this please

**Comment by yilongli** [comment]
Jenkins: retest this please

**Comment by yilongli** [comment]
@dwightguth @andreistefanescu The last commit becomes kind of unnecessary after discussion with Manasvi because I will gradually remove code related to the old debugger from the java backend.

**Comment by yilongli** [comment]
@dwightguth @andreistefanescu please review

**Comment by dwightguth** [comment]
lgtm

**Comment by andreistefanescu** [comment]
lgtm

**Pull request merged**
