### PR TITLE
Delete unused files from repo

### PR DESCRIPTION
**Pull request by dwightguth**
@traiansf @cos @yilongli @owolabileg Please review

### CODE REVIEW

**Comment by andreistefanescu** [comment]
Please leave the files in tutorial/1_k/5_types/experiments.

**Comment by dwightguth** [comment]
What are we using them for?

**Comment by grosu** [comment]
Just a general principle, without checking the details (I cannot check them now, due to urgent matters):

Everything under tutorial should be either fixed and stay, or otherwise removed!  If you are talking about sample/java-rewrite-engine, that is another story.

**Comment by owolabileg** [comment]
It is OK with me to remove those files from samples/java_rewrite_engine/tutorial/1_k/2_imp/indexing

**Comment by traiansf** [comment]
I'm generally not in favor of removing tests.  Couldn't we revive (at least some) of these tests?  I'm mostly concerned about the regression tests (issues).

**Comment by traiansf** [comment]
I'm ok with it as it is now. Maybe add an issue that those issues should be revisited and either removed or added back to testing so that we don't forget that they are there.

I think some of the issues are testing exceptional behavior, but since we did not have a way to detect that, they were not moved into regression

**Pull request merged**
