### PR TITLE
make PatternMatchRewriter the default

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
@grosu @yilongli please review

Note I elected to not do anything about the two tests (agent and issue709) which should have passed with the pattern match rewriter, but didn't. I don't have the resources to fix these issues now. Please let me know if you would like me to do anything to track them, however.

**Comment by yilongli** [comment]
OK, this is not good. I thought we ran these tests with both options. You should at least try to keep track of these issues.

**Comment by dwightguth** [comment]
@yilongli I can create an issue for this, the problem is I don't really know who to assign it to...

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by yilongli** [comment]
@dwightguth reopen issue709 and I will try to take a look when I have time. As for the agent, I think it's best to assign it to yourself.

**Comment by dwightguth** [comment]
okay. Sounds good, I will do that.

**Comment by dwightguth** [comment]
Cf #709 #1407

**Comment by dwightguth** [comment]
@yilongli are you okay with this being merged, or would you like me to do more?

**Comment by yilongli** [comment]
I am OK with it.

**Comment by grosu** [comment]
@lgtm

**Pull request merged**
