### PR TITLE
Preserve source location for KItem in KAbstractRewriteMachine

### LINKED ISSUE #1329: failed to preserve location information
The pattern-matching rewriting engine does not preserve the location information when a new term is generated by substitution.

For example,

```
  1 //require "builtins/int.k"
  2 
  3 module A
  4 
  5 //imports INT-HOOKS
  6 
  7 configuration <T>
  8   <k> $PGM:Cmds </k>
  9 </T>
 10 
 11 syntax Cmds ::= Cmd Cmds
 12               | Cmd
 13 syntax Cmd ::= "run1" "(" Int ")"
 14              | "run2" "(" Int ")"
 15 
 16 syntax KItem ::= "x" "(" Int ")"
 17                | "y" "(" Int ")"
 18 
 19 rule run1(N:Int) => x(N)
 20 
 21 rule run2(N:Int) => x(N)
 22 
 23 rule C:Cmd Cs:Cmds => C ~> Cs
 24 
 25 rule x(_:Int) => .
 26 
 27 endmodule
```

The right hand side term `x(N)` of line 19 and 21 does not have a location information.

It seems that the new term generated by substitution `N` does not preserve the location information properly. 

For example, the following line does not preserve the location information:
https://github.com/kframework/k/blob/ba807d532fcc9bdeadde645ecc67644265f2135c/java-backend/src/main/java/org/kframework/backend/java/rewritemachine/KAbstractRewriteMachine.java#L196

I think it should preserve the location information by using another `KItem.of`:
https://github.com/kframework/k/blob/ba807d532fcc9bdeadde645ecc67644265f2135c/java-backend/src/main/java/org/kframework/backend/java/kil/KItem.java#L74
But I have no idea how to find the place where the original location information is stored or lost.

Any idea? @yilongli @andreistefanescu

### PR DESCRIPTION
**Pull request by daejunpark**
Fix #1329 
Jenkins test first

### CODE REVIEW

**Comment by daejunpark** [comment]
Jenkins: test again

**Comment by daejunpark** [comment]
Jenkins test again please

**Comment by dwightguth** [comment]
The command is as follows. Note the difference in wording:

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
