### PR TITLE
hotfix/rename k core to kernel

### PR DESCRIPTION
**Pull request by cos**
**please review** if ktest passes

@dwightguth, let's make this in two steps. this is the k-core -> kernel rename

### CODE REVIEW

**Comment by cos** [comment]
I don't get this failure locally. @dwightguth, could you please have a look?

**Comment by dwightguth** [comment]
This  diff is still deleting the marker file we talked about yesterday, that is why the build is failing.

**Comment by cos** [comment]
ok, I force added it in the previous commit, but didn't after the split. let's see now.

**Comment by dwightguth** [comment]
lgtm

**Pull request merged**
