### PR TITLE
move assembly to verify goal so it can be run by pull requests build

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
@bmmoore please review

**Comment by andreistefanescu** [comment]
lgtm

**Comment by bmmoore** [comment]
I guess I'll trust @andreistefanescu  that "0" is the right count to report on a bound of zero.

I don't know maven or our build system enough to be sure I've understood the pom change. I guess it makes it zip things up as part of mvn verify, and moving that will make Jenkins cover stuff better? The commit would be _much_ better with a sentence or two explaining that, but unless you're going to amend that in I guess it's good to merge.

**Pull request merged**
