### PR TITLE
Fix for issue #2328

### PR DESCRIPTION
**Pull request by lucaspena**
With @msaxena2, add initialVariables to TermContext, rightOnlyVariables now calculated correctly by considering variables from initial term.

### CODE REVIEW

**Comment by msaxena2** [comment]
@cos @andreistefanescu Please review.

**Review by nishantjr — APPROVED** [review]
Looks good after we added the test.

**Comment by nishantjr** [comment]
The test isn't being run by the top-level ktest please hold on merging

**Comment by msaxena2** [comment]
@nishantjr The tests should run now.

**Pull request merged**
