### PR TITLE
Fix maude profiler support.

### PR DESCRIPTION
**Pull request by chathhorn**
The profiler needs to be turned on before rewriting. Also, there was a missing line separator.

### CODE REVIEW

**Comment by dwightguth** [comment]
Can you make a test for this so it doesn't happen again?

**Comment by chathhorn** [comment]
The test I added would catch the missing newline, but I'm not sure how to test the profiler more thoroughly using ktest. The profiler output only shows up with the "--output raw" option, which also causes things like timing information and filesystem paths to appear in the output. Is there some way to make ktest check the output against a regex instead of just straight equality?

**Comment by dwightguth** [comment]
checking against a regex actually sounds like a really useful feature. I
will make a pull request to add this functionality, then you can use it
once that pull,request is merged.

**Comment by dwightguth** [comment]
Please see #356 for information on how to write your test. It is now merged.

**Comment by chathhorn** [comment]
This is ready to be reviewed/merged again.

**Comment by dwightguth** [comment]
I will own understanding this. Merging.

**Pull request merged**
