### PR TITLE
Unified builtins2

### PR DESCRIPTION
**Pull request by andreistefanescu**

### CODE REVIEW

**Comment by dwightguth** [comment]
lgtm but I don't know anything about proofs. Maybe you could find someone a bit more familiar with what you're doing to review too?

**Comment by yilongli** [comment]
lgtm

**Comment by andreistefanescu** [comment]
@grosu please review.

**Comment by grosu** [comment]
lgtm for now; it is OK to merge.  I hope in the near future, though, we come up with a better notation for properties, including for calling functions with value arguments.

**Pull request merged**
