### PR TITLE
fixed ConcreteCollectionVariable#matchConcreteSize

### PR DESCRIPTION
**Pull request by yilongli**
fixed https://github.com/kframework/k/issues/979

@dwightguth please review

### CODE REVIEW

**Comment by dwightguth** [comment]
I don't understand what this function is supposed to do, so I can't independently verify that the change you made is correct. @andreistefanescu can you review?

**Comment by yilongli** [comment]
This function checks if a ConcreteCollectionVariable, i.e., a variable representing collection with fixed number of elements, can _match_ a given term, that is, the given term should not be narrowed.

**Comment by dwightguth** [comment]
So a ConcreteCollectionVariable always knows exactly how many elements it has, and that's what the concreteSize field is? But then a variable with size 5 should be able to match a set with 4 elements and a variable. So why was this wrong?

**Comment by yilongli** [comment]
Because in your example a variable with size 5 is the pattern, while a set with 4 elements and a variable is the subject, you actually require the variable in the subject to have only one element. The subject is then narrowed.

**Comment by dwightguth** [comment]
lgtm

**Comment by andreistefanescu** [comment]
@yilongli I think this change makes SymbolicConstraint.EqualityOperations#isFalse and SymbolicUnifier#unify incorrect. The change in behavior should only apply in the PatternMatcher.

**Comment by yilongli** [comment]
@andreistefanescu please review again.

**Comment by andreistefanescu** [comment]
lgtm

**Comment by yilongli** [comment]
Jenkins: retest this please

**Pull request merged**
