### PR TITLE
[em] Unexpected isBag predicate not of arity 1 found

### PR DESCRIPTION
**Pull request by daejunpark**
from k-3.6/kernel/src/main/java/org/kframework/kore/compile/SortCells.java:322-324

### CODE REVIEW

**Comment by daejunpark** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
@bmmoore please review

**Comment by bmmoore** [comment]
Looks good for adding back that error message. I don't think we have any cases that trigger it unless you just explicitly write an invalid isBag application in a condition, and I'm not sure what testing we need for error messages, so I'm just merging this change now. 

If there was an actual bug with some definition where this message would have been helpful we can reconsider testing, but if you are just restoring old error behavior it looks fine to me.

**Comment by bmmoore** [comment]
oops, need to merge then close.

**Comment by daejunpark** [comment]
#1945

**Pull request merged**
