### PR TITLE
Issue#596

### PR DESCRIPTION
**Pull request by radumereuta**
Fixing issue #596 
Also #595 should be merged at the same time with this one.

### CODE REVIEW

**Comment by yilongli** [comment]
I made a mistake when creating https://github.com/kframework/k/pull/595. I closed it and created a new one at https://github.com/kframework/k/pull/600.

**Comment by dwightguth** [comment]
Per our discussion, the correct solution is to remove sort BagItem.

**Comment by yilongli** [comment]
What is the sort of a cell, if not BagItem? Bag? I am not sure I understand why removing sort BagItem is the correct solution.

**Comment by radumereuta** [comment]
Apparently it isn't.
I'm not sure what is the correct solution.

**Comment by yilongli** [comment]
In case it's indeed the correct solution, which I doubt, I can take care of the failing tests for the Java backend.

**Comment by grosu** [comment]
I don't remember when removing the sort BagItem was discussed ... Anyway, we do not have bandwidth for innovations now; all we want is to merge unified-builtins2 asap, without losing anything we had before.  Any other design decisions can be applied afterwards.

**Comment by dwightguth** [comment]
We removed MapItem, SetItem, ListItem. Why not BagItem?

**Comment by grosu** [comment]
Oh, the sorts, sorry, I thought the wrappers.  So we still write ListItem(X) => Y, but we are not allowed to write X:ListItem => Y.  Yes, I knew that and it makes sense.

But now getting back to Yilong's original question: "What is the sort of a cell, if not BagItem? Bag?".  Yilong, do you need to match generically on one cell?  We need to re-design the entire configuration syntax and internal representation soon anyway, so maybe this can wait until then?  But if you really need the BagItem sort right now, then please let us know.

**Comment by dwightguth** [comment]
You do not. in the worst case you can always say `B:Bag when size(B) ==Int
1`

**Comment by yilongli** [comment]
I think in terms of how the Java backend works. The Java backend might still use BagItem in several places. I don't think I need BagItem. But I will have to look at the source code to understand what goes wrong.

**Comment by dwightguth** [comment]
I no longer want to insist on a large scale refactoring of our use of Bag at this time, but if there's still a bug here, can it get fixed?

**Comment by radumereuta** [comment]
I plan to have another look at it after I'm done with the type inferencer.
I'm still thinking how to handle the sort for rewrites, and it should be ready to be merge.

**Comment by radumereuta** [comment]
Let's delay solving the BagItem issue for the new kast.
I would have to go too much into SDF to fix it, and it won't bring us too much benefit.

**Pull request closed without merging**
