### PR TITLE
kompile fun-untyped environment

### PR DESCRIPTION
**Pull request by andreistefanescu**
do not review yet

### CODE REVIEW

**Comment by andreistefanescu** [comment]
@radumereuta I get some weird error messages if I do not comment lines 331-332, the subsorting with klabels. Could you please take a look?

**Comment by cos** [comment]
@andreistefanescu, it shouldn't affect anything, but you could try removing the quotes from all klabels

**Comment by cos** [comment]
Jenkins: test this please

**Comment by andreistefanescu** [comment]
@grosu I have takes the environment based fun to the point where all tests that parse also execute successfully. Please review what I have done so far. I will move on to fixing the `matchAssoc` exception now. If you have spare cycles and want to modify the definition further/try to see whay the 7 programs do not parse, you can go ahed. I will not touch this definition in the immediate future.

**Comment by grosu** [comment]
@andreistefanescu , this looks good.  I like it that you managed to do the entire thing in K.  I don't like the outputs, but those will be improved later when we have a better unparser.  I looked a bit into the parsing issue and I could not figure it out quickly.  I am also very tired, as I woke up early in the morning and had little sleep.  Parsing comes with lots of headaches, and you need a fresh mind for that.

**Comment by andreistefanescu** [comment]
@grosu I added the substitution-based fun (the last 2 commits). Please review them as well.
@cos please review https://github.com/kframework/k/commit/9ce900820a485fc9fe2eadbdd7f194c1abfb6a1a

**Comment by cos** [comment]
lgtm

**Comment by grosu** [comment]
looks good!  so the only thing left is that parsing thingy.

**Pull request merged**
