### PR TITLE
MInt not considered when loading configuration into spec rules

### PR DESCRIPTION
**Pull request by daejunpark**
@andreistefanescu please review

### CODE REVIEW

**Comment by daejunpark** [comment]
@andreistefanescu Do I need to consider this as well?
https://github.com/kframework/k/blob/master/java-backend/src/main/java/org/kframework/backend/java/symbolic/KILtoBackendJavaKILTransformer.java#L174

**Comment by andreistefanescu** [comment]
`KILtoBackendJavaKILTransformer.java` is dead code, so don't worry about it.

Are you trying to add syntax for machine integers?

**Comment by daejunpark** [comment]
No, this fixes a bug that occurs when K prover loads and replaces configuration cells with place-holder variables in spec rules. For example, suppose we have `<memory> MEMORY:Map </memory>` in a spec rule, and `MEMORY` is supposed to be replaced with a map containing machine integers. In this case, the machine integers are loaded as UninterpretedToken instead of BitVector.

**Comment by cos** [comment]
is this ready for review/merging?

**Comment by daejunpark** [comment]
yes, it is.

**Pull request merged**
