### PR TITLE
fix typo in readme

### PR DESCRIPTION
**Pull request by dwightguth**
**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
Jenkins: test C semantics

**Comment by dwightguth** [comment]
@grosu can you review this quickly? it's basically just a typo fix that I took advantage of in order to test the Jenkins build infrastructure.

**Comment by grosu** [comment]
lgtm

**Pull request merged**
