### PR TITLE
clean up some ugliness in UnparserFilterNew

### PR DESCRIPTION
**Pull request by dwightguth**
@liyili2 please review.

### CODE REVIEW

**Comment by liyili2** [comment]
What is the problem of UnparserFilterNew??

**Comment by dwightguth** [comment]
So the reason I made this is because the findRightSyntax method introduces a dependency on the entire definition at unparsing time even though the only thing it truly needs is information about the bracket productions and subsorts in the definition. I am trying to break the dependency on the entire definition in krun to speed up initialization. In order to do this it was necessary to move the information you were looking for to the Context object where it belongs.

**Comment by liyili2** [comment]
Does the krun parser use the UnparserFilterNew? I do not think so.

**Comment by dwightguth** [comment]
I don't understand what you're asking here. Neither this pull request nor the bug report I created have anything to do with the krun parser. The point of this pull request is to break the dependency of the UnparserFilterNew on the serialized Definition object, and to bring the functionality it provides in line with the preexisting design pattern for storing metadata about a compiled definition. This pull request is a refactoring only: it should not affect functionality at all. The fact that the current functionality is broken is a separate issue, which is why I assigned it to you instead of spending days trying to fix it myself, when it's not my priority.

**Comment by liyili2** [comment]
Sorry, I put the things in wrong place. What should I do for the pull request after review?

**Comment by dwightguth** [comment]
If you feel like you understand what the change is doing, approve it and I
will merge it.

**Pull request merged**
