### PR TITLE
ksequence normalization

### PR DESCRIPTION
**Pull request by dwightguth**
Remaking Manasvi's pull request, I have fixed the comments from the other PR. @cos please re-review.

I tested the performance on IMP sum to 10000 and it's not any slower with this change. I can test with a more complex semantics also if you'd like.

### CODE REVIEW

**Comment by dwightguth** [comment]
See #1911 for previous discussion.

**Comment by cos** [comment]
thanks @dwightguth for picking this up!

**Comment by cos** [comment]
Jenkins: test this please

**Comment by cos** [comment]
the performance test should be enough -- just wanted to make sure there isn't something we're not seeing.

**Comment by cos** [comment]
Jenkins: test this please

**Comment by cos** [comment]
I think that failure was non-determinism

**Pull request merged**
