### PR TITLE
modify whitespace rules for data structures in unparser

### PR DESCRIPTION
**Pull request by dwightguth**
@yilongli please review

### CODE REVIEW

**Comment by yilongli** [comment]
lgtm. Have you tested it to make sure it works as expected?

**Comment by dwightguth** [comment]
See for yourself:

```
dwightguth@rvwork-1:~/test$ krun -cPGM="SetItem(SetItem(5))"
<k>
    SetItem ( SetItem ( 5 ) )
</k>
dwightguth@rvwork-1:~/test$ krun -cPGM="SetItem(SetItem(5) SetItem(6))"
<k>
    SetItem ( 
        SetItem ( 5 )
        SetItem ( 6 ) )
</k>
dwightguth@rvwork-1:~/test$ krun -cPGM="SetItem(SetItem(5) SetItem(6)) SetItem(7)"
<k>
    SetItem ( 7 )
    SetItem ( 
        SetItem ( 5 )
        SetItem ( 6 ) )
</k>
dwightguth@rvwork-1:~/test$ krun -cPGM="5 |-> (6 |-> 7 9 |-> 78) 6 |-> 7"
<k>
    5 |-> 
        6 |-> 7
        9 |-> 78
    6 |-> 7
</k>
dwightguth@rvwork-1:~/test$ krun -cPGM="1 ~> 5 |-> (6 |-> 7 9 |-> 78) 6 |-> 7"
<k>
    1 ~> 5 |-> 
        6 |-> 7
        9 |-> 78
    6 |-> 7
</k>
```

Satisfactory?

**Comment by yilongli** [comment]
The output seems very nice. However, I do not understand why the merge build timed out.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
