### PR TITLE
improve intermediate debugging messages printed by the prover

### PR DESCRIPTION
**Pull request by yilongli**
Something I did in the past is unnecessary. It only makes the intermediate results of rewriter/prover really hard to read.

### CODE REVIEW

**Comment by yilongli** [comment]
@andreistefanescu @dwightguth please review

**Comment by dwightguth** [comment]
lgtm. Andrei?

**Comment by andreistefanescu** [comment]
lgtm

**Comment by dwightguth** [comment]
@yilongli can you fix the conflicts?

**Pull request merged**
