### PR TITLE
Issue #1335 Fix

### PR DESCRIPTION
**Pull request by msaxena2**
Small changes to fix Issue #1335. State of fresh counters problem solved problem solved. Do not review yet.

### CODE REVIEW

**Comment by msaxena2** [comment]
Jenkins: test this please

**Comment by msaxena2** [comment]
Jenkins: test this please

**Comment by msaxena2** [comment]
@dwightguth please review

**Comment by dwightguth** [comment]
looks good. I'm going to merge this. Eventually we will want to remake the Executor interface over KORE, although it may be slightly different by then. That will be when we remove these extra methods, which I've decided aren't that nice. But it's fine for now as a fix for Traian's problem.

**Pull request merged**
