### PR TITLE
abstract `map` better

### PR DESCRIPTION
**Pull request by cos**
**please review** @dwightguth, @osa1

### CODE REVIEW

**Comment by osa1** [comment]
I'm worried about implementing things other than data structures in Scala ... but lgtm.

**Comment by cos** [comment]
This is just the data structures. 'map' is a basic operation on KCollections.

(sent from mobile phone)

**Comment by pdaian** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
lgtm

**Pull request merged**
