### PR TITLE
Substantial optimizations to OCAML backend

### PR DESCRIPTION
**Pull request by dwightguth**
@bmmoore @radumereuta @cos please review

This is probably my last commit to the OCAML backend for now. Everything seems to work well and it performs at roughly 250,000x C, which is roughly 90-100x the Java backend. Substantial further performance results will have to come from something like partial compilation to decrease the number of rules tried and applied.

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by bmmoore** [comment]
Looks good to me.

**Comment by dwightguth** [comment]
I have merged this since I haven't heard anything from @radumereuta or @cos . Please feel free to make comments if you wish and I can try to address them in a future pull request.

**Comment by cos** [comment]
look good.

**Pull request merged**
