### PR TITLE
Hotfix/fix scala warnings

### PR DESCRIPTION
**Pull request by cos**

### CODE REVIEW

**Comment by cos** [comment]
review after #1697

**Comment by grosu** [comment]
I didn't follow the details, but it surprises me that so many changes were needed to fix the warnings.  But thanks for fixing them!

**Comment by cos** [comment]
The PL request applies over #1697. Once #1697 is merged, the diff will be much smaller.

**Comment by cos** [comment]
@bmmoore, please review. Overall, cleaned the Scala warnings, added flags to show more detailed warnings for deprecation and advanced feature usage, and made mvn ignore some irrelevant warnings related to the Scala version required by dependencies.

**Comment by bmmoore** [comment]
Looks good. `master..f0529fd` gives a reasonably small diff.

**Pull request merged**
