### PR TITLE
add better guice scoping in order to share definition deserialization ac...

### PR DESCRIPTION
**Pull request by dwightguth**
...ross invocations in a server

**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@yilongli please review

This diff drops the time to run the torture test for the C semantics from 12 minutes to 8 minutes.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by yilongli** [comment]
lgtm

**Comment by grosu** [comment]
This is great!  I hope we will eventually get the same cool performance improvements with ktest as well.

**Comment by dwightguth** [comment]
KTest is actually pretty fast to run on the integration tests in the framework now. My most recent run with this diff took 5 minutes, which is pretty close to optimal for a set of integration tests. I can do more profiling, but honestly this isn't where our biggest performance concerns are anymore. The major concern is performance on programs with lots and lots of steps, or with very very large configurations. And these will continue to improve as I work on profiling the C semantics.

**Comment by dwightguth** [comment]
Uncovered some new race conditions. :/ Gonna run it again. Looking forward to the day I can try RV-predict on K!

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@yilongli I fixed the race conditions. There were two: one was fixed by adding a synchronized block in SimpleScope, the other was fixed by adding a static lock on functions that use IncrementalCollector in the java backend. The latter was caused because the new scoping rules caused two programs to share the same Definition object, and there were races on their mutable fields.

Can you please re-review so I can merge this finally?

**Comment by yilongli** [comment]
LGTM. I will make sure rv-predict catch these two races once I am done with my current task.

**Comment by yilongli** [comment]
@dwightguth Are you sure that the synchronized block on `scopedObjects` you added in b452074 is necessary? Since `scopedObjects` is obtained from `InheritableThreadLocal<Map<Key<?>, Object>> values`, there shouldn't be any race on it, right? I am looking at the trace produced by rv-predict and it does look like every thread has its own `scopedObjects`.

**Comment by yilongli** [comment]
And here is the race report regarding `JavaSymbolicObject.variableSet` generated by rv-predict:
(I have marked the interesting part of the stacktrace with `---->`)

```
Possible data race on field org.kframework.backend.java.kil.JavaSymbolicObject.variableSet: {{{
    Concurrent read in thread T16 (locks held: {})
        at org.kframework.backend.java.kil.JavaSymbolicObject.getVariableSet(JavaSymbolicObject.java:223)
        at org.kframework.backend.java.kil.JavaSymbolicObject.lambda$variableSet$2(JavaSymbolicObject.java:122)
        at org.kframework.backend.java.kil.JavaSymbolicObject$$Lambda$52.apply(Unknown:n/a)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:157)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:69)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:64)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.CombinedLocalVisitor.visitAll(CombinedLocalVisitor.java:51)
        at org.kframework.backend.java.symbolic.CombinedLocalVisitor.visit(CombinedLocalVisitor.java:84)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.PrePostVisitor.visit(PrePostVisitor.java:91)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.PrePostVisitor.visit(PrePostVisitor.java:94)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
  ----> at org.kframework.backend.java.kil.JavaSymbolicObject.variableSet(JavaSymbolicObject.java:129)
        at org.kframework.backend.java.kil.JavaSymbolicObject.isGround(JavaSymbolicObject.java:56)
        at org.kframework.backend.java.rewritemachine.GenerateRHSInstructions.visit(GenerateRHSInstructions.java:114)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.kil.Rule.<init>(Rule.java:205)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformAndEval(KILtoBackendJavaKILTransformer.java:120)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.search(JavaSymbolicExecutor.java:116)
        at org.kframework.krun.tools.Executor$Tool.search(Executor.java:153)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:124)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
        at org.kframework.main.Main.runApplication(Main.java:110)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:71)
    T16 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T65 (locks held: {})
        at org.kframework.backend.java.kil.JavaSymbolicObject.setVariableSet(JavaSymbolicObject.java:227)
        at org.kframework.backend.java.kil.JavaSymbolicObject.lambda$variableSet$1(JavaSymbolicObject.java:121)
        at org.kframework.backend.java.kil.JavaSymbolicObject$$Lambda$48.accept(Unknown:n/a)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:157)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:69)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:64)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.CombinedLocalVisitor.visitAll(CombinedLocalVisitor.java:51)
        at org.kframework.backend.java.symbolic.CombinedLocalVisitor.visit(CombinedLocalVisitor.java:84)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.PrePostVisitor.visit(PrePostVisitor.java:91)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.PrePostVisitor.visit(PrePostVisitor.java:94)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
  ----> at org.kframework.backend.java.kil.JavaSymbolicObject.variableSet(JavaSymbolicObject.java:129)
        at org.kframework.backend.java.kil.JavaSymbolicObject.isGround(JavaSymbolicObject.java:56)
        at org.kframework.backend.java.rewritemachine.GenerateRHSInstructions.visit(GenerateRHSInstructions.java:114)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.kil.Rule.<init>(Rule.java:205)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformAndEval(KILtoBackendJavaKILTransformer.java:120)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.search(JavaSymbolicExecutor.java:116)
        at org.kframework.krun.tools.Executor$Tool.search(Executor.java:153)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:124)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
        at org.kframework.main.Main.runApplication(Main.java:110)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:71)
    T65 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

Again, I am running rv-predict against revision ed955d7. Here is the source code of JavaSymbolicObject at this moment: https://github.com/dwightguth/k/blob/ed955d76d5888891a89ed46b18ef2c46a3be31c5/java-backend/src/main/java/org/kframework/backend/java/kil/JavaSymbolicObject.java

**Comment by yilongli** [comment]
Similarly, the race report for `JavaSymbolicObject.functionKLabels`:

```
Possible data race on field org.kframework.backend.java.kil.JavaSymbolicObject.functionKLabels: {{{
    Concurrent write in thread T16 (locks held: {})
        at org.kframework.backend.java.kil.JavaSymbolicObject.lambda$isNormal$5(JavaSymbolicObject.java:174)
        at org.kframework.backend.java.kil.JavaSymbolicObject$$Lambda$59.accept(Unknown:n/a)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:157)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:69)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:64)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.CombinedLocalVisitor.visitAll(CombinedLocalVisitor.java:51)
        at org.kframework.backend.java.symbolic.CombinedLocalVisitor.visit(CombinedLocalVisitor.java:84)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.PrePostVisitor.visit(PrePostVisitor.java:91)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.PrePostVisitor.visit(PrePostVisitor.java:94)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.kil.JavaSymbolicObject.isNormal(JavaSymbolicObject.java:189)
        at org.kframework.backend.java.rewritemachine.GenerateRHSInstructions.visit(GenerateRHSInstructions.java:114)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.kil.Rule.<init>(Rule.java:205)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformAndEval(KILtoBackendJavaKILTransformer.java:120)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.search(JavaSymbolicExecutor.java:116)
        at org.kframework.krun.tools.Executor$Tool.search(Executor.java:153)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:124)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
        at org.kframework.main.Main.runApplication(Main.java:110)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:71)
    T16 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T65 (locks held: {})
        at org.kframework.backend.java.kil.JavaSymbolicObject.lambda$isNormal$5(JavaSymbolicObject.java:174)
        at org.kframework.backend.java.kil.JavaSymbolicObject$$Lambda$59.accept(Unknown:n/a)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:157)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:69)
        at org.kframework.backend.java.symbolic.LocalVisitor.visit(LocalVisitor.java:64)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.CombinedLocalVisitor.visitAll(CombinedLocalVisitor.java:51)
        at org.kframework.backend.java.symbolic.CombinedLocalVisitor.visit(CombinedLocalVisitor.java:84)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.PrePostVisitor.visit(PrePostVisitor.java:91)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.symbolic.PrePostVisitor.visit(PrePostVisitor.java:94)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.kil.JavaSymbolicObject.isNormal(JavaSymbolicObject.java:189)
        at org.kframework.backend.java.rewritemachine.GenerateRHSInstructions.visit(GenerateRHSInstructions.java:114)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:300)
        at org.kframework.backend.java.kil.Rule.<init>(Rule.java:205)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformAndEval(KILtoBackendJavaKILTransformer.java:120)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.search(JavaSymbolicExecutor.java:116)
        at org.kframework.krun.tools.Executor$Tool.search(Executor.java:153)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:124)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
        at org.kframework.main.Main.runApplication(Main.java:110)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:71)
    T65 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
I haven't got similar race report on `JavaSymbolicObject.userVariableSet`. Maybe it is because running ktest on `1_k/1_lambda/lesson_1` is not enough? Anyway, I am still looking into that. 

**update:** yes, `1_k/1_lambda/lesson_1` doesn't exercise that part of the code.

**Pull request merged**
