### PR TITLE
updated simple typed dynamic to work with unified-builtins2

### PR DESCRIPTION
**Pull request by grosu**
SIMPLE is completely updated now

### CODE REVIEW

**Comment by yilongli** [comment]
lgtm

**Comment by dwightguth** [comment]
pretty sure the conflict is in config.xml and is really easy to fix. If you fix it, @grosu, you can merge.

**Comment by grosu** [comment]
Sorry, what conflict?  I do not see it listed/published anywhere.  Indeed, there could be issues with the config.xml files, because I tried to make each update independent from the others, and not one on top of the previous one, to make their merge independent.  If you can briefly explain me what I need to do to see the conflict I will do it right away.

Grigore

**Comment by dwightguth** [comment]
I can't merge this automatically because there are conflicts. I would probably have had to do an octopus merge in order to get the behavior you're describing. In the future, if you think that you might have diffs that conflict with each other, please construct them in such a way that there is some specific linear order I can merge them in, and then tell me that order.

You need to:
1. Run `git merge unified-builtins2` in your branch.
2. Resolve conflicts.
3. Push the merge commit.

**Comment by dwightguth** [comment]
Okay. You can merge this if tests pass.

**Pull request merged**
