### PR TITLE
clean up maude runner and io server

### PR DESCRIPTION
**Pull request by dwightguth**
@yilongli please review

I know you aren't familiar with this part of the code, but neither is anyone else on the team. Just give it your best shot.

### CODE REVIEW

**Comment by dwightguth** [comment]
Never mind, hold off on reviewing, I want to make some more changes.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@yilongli please review

**Comment by yilongli** [comment]
lgtm

**Pull request merged**
