### PR TITLE
Performance improvements to krun

### PR DESCRIPTION
**Pull request by dwightguth**
- stream outputs directly to and from files in many cases to save memory usage
- remove old --output raw so that the java backend does not invoke the unparser unnecessarily.
- other minor performance enhancements

**please review**

### CODE REVIEW

**Comment by dwightguth** [comment]
@yilongli please review

**Comment by yilongli** [comment]
lgtm

**Comment by grosu** [comment]
@dwightguth if there are any visible performance improvements for users of the K framework, can you please briefly let us know what kind of improvements and how much?

**Comment by dwightguth** [comment]
It's not that noticeable for most users of the semantics. Mosly the case I am improving is the case where users have very very very large configurations, in which case some of the changes here are meant to speed up the semantics and/or prevent crashes.

**Pull request merged**
